// src/lib/citiesData.ts

export interface City {
    id: string;
    name: string;
    category: 'city' | 'neighborhood';
    parentCity?: string; // for neighborhoods
}

export const cities: City[] = [
    // ערים ואזורים ראשיים
    { id: 'ashkelon', name: 'אשקלון', category: 'city' },
    { id: 'ashkelon-neighborhood-afridar', name: 'אשקלון - שכונת אפרידר', category: 'neighborhood', parentCity: 'ashkelon' },
    { id: 'ashkelon-neighborhood-shimshon', name: 'אשקלון - שכונת שמשון', category: 'neighborhood', parentCity: 'ashkelon' },
    { id: 'ashdod', name: 'אשדוד', category: 'city' },
    { id: 'beersheba', name: 'באר שבע', category: 'city' },
    { id: 'beersheba-old-city', name: 'באר שבע - העיר העתיקה', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-south', name: 'באר שבע - שכונת דרום', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-downtown', name: 'באר שבע - הדאון טאון (המרכז האזרחי)', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-n1', name: 'באר שבע - שכונה א\'', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-n2', name: 'באר שבע - שכונה ב\'', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-n3', name: 'באר שבע - שכונה ג\'', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-n4', name: 'באר שבע - שכונה ד\'', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-n5', name: 'באר שבע - שכונה ה\'', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-n6', name: 'באר שבע - שכונה ו\'', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-n9', name: 'באר שבע - שכונה ט\'', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-n11', name: 'באר שבע - שכונה י"א', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-naot-lon', name: 'באר שבע - נאות לון', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-naveh-zaev', name: 'באר שבע - נווה זאב', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-naveh-noy', name: 'באר שבע - נווה נוי', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-nachal-baka', name: 'באר שבע - נחל בקע', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-nachal-ashen', name: 'באר שבע - נחל עשן (נווה מנחם)', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-sigliyot', name: 'באר שבע - שכונת הסיגליות', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-ramot', name: 'באר שבע - רמות', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-naot-avraham', name: 'באר שבע - נאות אברהם', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-naveh-ilan', name: 'באר שבע - נווה אילן (פלח 7)', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-kiryat-ganim', name: 'באר שבע - שכונת קריית גנים', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beersheba-kalniyt', name: 'באר שבע - שכונת הכלניות', category: 'neighborhood', parentCity: 'beersheba' },
    { id: 'beit-shemesh', name: 'בית שמש', category: 'city' },
    { id: 'bat-yam', name: 'בת ים', category: 'city' },
    { id: 'bat-yam-ramat-yossef', name: 'בת ים - רמת יוסף', category: 'neighborhood', parentCity: 'bat-yam' },
    { id: 'bat-yam-kiryat-babub', name: 'בת ים - קריית באבוב', category: 'neighborhood', parentCity: 'bat-yam' },
    { id: 'bne-barak', name: 'בני ברק', category: 'city' },
    { id: 'bne-barak-or-hachaim', name: 'בני ברק - אור החיים', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-givat-rokach', name: 'בני ברק - גבעת רוקח', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-gani-gad', name: 'בני ברק - גני גד', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-har-shalom', name: 'בני ברק - הר שלום', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-zichron-meir', name: 'בני ברק - זכרון מאיר', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-naveh-achiizer', name: 'בני ברק - נוה אחיעזר', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-pardes-katz', name: 'בני ברק - פרדס כץ', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-kiryat-herzog', name: 'בני ברק - קריית הרצוג', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-kiryat-vizhnitz', name: 'בני ברק - קריית ויז\'ניץ', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-kiryat-nadborny', name: 'בני ברק - קריית נדבורנה', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-ramat-aharan', name: 'בני ברק - רמת אהרן', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-ramat-elchanan', name: 'בני ברק - רמת אלחנן', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-shikun-5', name: 'בני ברק - שיכון ה\'', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-shikun-histadrut', name: 'בני ברק - שיכון ההסתדרות', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-shikun-6', name: 'בני ברק - שיכון ו\'', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-shikun-chazon-ish', name: 'בני ברק - שיכון חזון איש', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'bne-barak-tel-gibborim', name: 'בני ברק - תל גיבורים', category: 'neighborhood', parentCity: 'bne-barak' },
    { id: 'hadera', name: 'חדרה', category: 'city' },
    { id: 'hadera-beit-eliezer', name: 'חדרה - בית אליעזר', category: 'neighborhood', parentCity: 'hadera' },
    { id: 'hadera-brandeis', name: 'חדרה - ברנדייס', category: 'neighborhood', parentCity: 'hadera' },
    { id: 'hadera-givat-olga', name: 'חדרה - גבעת אולגה', category: 'neighborhood', parentCity: 'hadera' },
    { id: 'hadera-naveh-chaim', name: 'חדרה - נווה חיים', category: 'neighborhood', parentCity: 'hadera' },
    { id: 'hadera-nachliel', name: 'חדרה - נחליאל', category: 'neighborhood', parentCity: 'hadera' },
    { id: 'holon', name: 'חולון', category: 'city' },
    { id: 'holon-agrobank', name: 'חולון - אגרובנק', category: 'neighborhood', parentCity: 'holon' },
    { id: 'holon-jessi-cohen', name: 'חולון - ג\'סי כהן', category: 'neighborhood', parentCity: 'holon' },
    { id: 'holon-naveh-pinhas', name: 'חולון - נווה פנחס', category: 'neighborhood', parentCity: 'holon' },
    { id: 'holon-kiryat-avoda', name: 'חולון - קריית עבודה', category: 'neighborhood', parentCity: 'holon' },
    { id: 'holon-kiryat-seret', name: 'חולון - קריית שרת', category: 'neighborhood', parentCity: 'holon' },
    { id: 'holon-tel-gibborim', name: 'חולון - תל גיבורים', category: 'neighborhood', parentCity: 'holon' },
    { id: 'haifa', name: 'חיפה', category: 'city' },
    { id: 'haifa-ramat-ashkol', name: 'חיפה - רמת אשכול', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-vardia', name: 'חיפה - ורדיה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-begin', name: 'חיפה - רמת בגין', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-sapir', name: 'חיפה - רמת ספיר', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-alon', name: 'חיפה - רמת אלון', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramot-ramez', name: 'חיפה - רמות רמז', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-golda', name: 'חיפה - רמת גולדה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-almogi', name: 'חיפה - רמת אלמוגי', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-carmel-quarter', name: 'חיפה - רובע כרמל', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-carmel-francais', name: 'חיפה - כרמל צרפתי', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-west', name: 'חיפה - מערב חיפה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-bay-quarter', name: 'חיפה - רובע המפרץ', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-kiryat-eliezer', name: 'חיפה - קריית אליעזר', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-kiryat-shmuel', name: 'חיפה - קריית שמואל', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramot-hacarmel', name: 'חיפה - רובע רמות הכרמל', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ahuzat-shmuel', name: 'חיפה - אחוזת שמואל', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ard-alyahud', name: 'חיפה - ארד אל-יהוד', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-bat-galim', name: 'חיפה - בת גלים', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-givat-arannim', name: 'חיפה - גבעת אורנים', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-dania', name: 'חיפה - דניה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-dar-hacarmel', name: 'חיפה - הדר הכרמל', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-german-colony', name: 'חיפה - המושבה הגרמנית', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-upper-city', name: 'חיפה - העיר העליונה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-lower-city', name: 'חיפה - העיר התחתית', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-wadi-nisnas', name: 'חיפה - ואדי ניסנאס', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-wadi-salib', name: 'חיפה - ואדי סאליב', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-halisa', name: 'חיפה - חליסה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-kabeer', name: 'חיפה - כבאביר', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-kfar-samir', name: 'חיפה - כפר סמיר', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-carmel-west', name: 'חיפה - כרמל מערבי', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-carmel-center', name: 'חיפה - מרכז הכרמל', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-naot-peres', name: 'חיפה - נאות פרס', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-naveh-david', name: 'חיפה - נווה דוד', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-naveh-shanan', name: 'חיפה - נווה שאנן', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-nachla', name: 'חיפה - נחלה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-kiryat-haim', name: 'חיפה - קריית חיים', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-kiryat-sprintzak', name: 'חיפה - קריית שפרינצק', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-romena', name: 'חיפה - רוממה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-almogi2', name: 'חיפה - רמת אלמוגי', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-golda2', name: 'חיפה - רמת גולדה', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-nasi', name: 'חיפה - רמת הנשיא', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-ramat-vizhnitz', name: 'חיפה - רמת ויז\'ניץ', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'haifa-tachanat-carmel', name: 'חיפה - תחנת הכרמל', category: 'neighborhood', parentCity: 'haifa' },
    { id: 'tiberias', name: 'טבריה', category: 'city' },
    { id: 'tiberias-heharim', name: 'טבריה - חצר היהודים', category: 'neighborhood', parentCity: 'tiberias' },
    { id: 'tiberias-kiryat-tzanz', name: 'טבריה - קריית צאנז', category: 'neighborhood', parentCity: 'tiberias' },
    { id: 'tiberias-kiryat-shmuel', name: 'טבריה - קריית שמואל', category: 'neighborhood', parentCity: 'tiberias' },
    { id: 'tiberias-three-houses', name: 'טבריה - שכונת שלושת הבתים', category: 'neighborhood', parentCity: 'tiberias' },
    { id: 'ofakim', name: 'אופקים', category: 'city' },
    { id: 'ofakim', name: 'אופקים', category: 'city' },
    { id: 'kiryat-ono', name: 'קריית אונו', category: 'city' },
    { id: 'kiryat-gat', name: 'קריית גת', category: 'city' },
    { id: 'kiryat-malachi', name: 'קריית מלאכי', category: 'city' },
    { id: 'kiryat-motzkin', name: 'קריית מוצקין', category: 'city' },
    { id: 'kiryat-yam', name: 'קריית ים', category: 'city' },
    { id: 'kiryat-ata', name: 'קריית אתא', category: 'city' },
    { id: 'lod', name: 'לוד', category: 'city' },
    { id: 'lod-gani-aviv', name: 'לוד - גני אביב', category: 'neighborhood', parentCity: 'lod' },
    { id: 'lod-gani-ayalon', name: 'לוד - גני איילון', category: 'neighborhood', parentCity: 'lod' },
    { id: 'lod-rakevet', name: 'לוד - שכונת הרכבת', category: 'neighborhood', parentCity: 'lod' },
    { id: 'modiin-makabim-reut', name: 'מודיעין מכבים רעות', category: 'city' },
    { id: 'modiin-makabim-reut-mear', name: 'מודיעין מכבים רעות - מע"ר', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-karmin', name: 'מודיעין מכבים רעות - הכרמים', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-tzipor', name: 'מודיעין מכבים רעות - הציפורים', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-morya', name: 'מודיעין מכבים רעות - מוריה', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-maginim', name: 'מודיעין מכבים רעות - המגינים', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-shvatim', name: 'מודיעין מכבים רעות - השבטים', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-neviim', name: 'מודיעין מכבים רעות - הנביאים', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-moshua', name: 'מודיעין מכבים רעות - משואה', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-avni-chen', name: 'מודיעין מכבים רעות - אבני חן', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-shomer', name: 'מודיעין מכבים רעות - שומרי החומות', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-nachalim', name: 'מודיעין מכבים רעות - הנחלים', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-buchman', name: 'מודיעין מכבים רעות - בוכמן', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-kaiser', name: 'מודיעין מכבים רעות - קייזר', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-makabim-reut-shmoni', name: 'מודיעין מכבים רעות - שמשוני', category: 'neighborhood', parentCity: 'modiin-makabim-reut' },
    { id: 'modiin-elite', name: 'מודיעין עילית', category: 'city' },
    { id: 'modiin-elite-kiryat-sefer', name: 'מודיעין עילית - קרית ספר', category: 'neighborhood', parentCity: 'modiin-elite' },
    { id: 'modiin-elite-berkfeld', name: 'מודיעין עילית - ברכפלד', category: 'neighborhood', parentCity: 'modiin-elite' },
    { id: 'modiin-elite-naot-hasegia', name: 'מודיעין עילית - נאות הפסגה', category: 'neighborhood', parentCity: 'modiin-elite' },
    { id: 'modiin-elite-green-park', name: 'מודיעין עילית - גרין פארק', category: 'neighborhood', parentCity: 'modiin-elite' },
    { id: 'modiin-elite-chaftziba', name: 'מודיעין עילית - חפציבה', category: 'neighborhood', parentCity: 'modiin-elite' },
    { id: 'netanya', name: 'נתניה', category: 'city' },
    { id: 'netanya-naot-herzel', name: 'נתניה - נאות הרצל', category: 'neighborhood', parentCity: 'netanya' },
    { id: 'netanya-ir-yamim', name: 'נתניה - עיר ימים', category: 'neighborhood', parentCity: 'netanya' },
    { id: 'netanya-kiryat-nordau', name: 'נתניה - קריית נורדאו', category: 'neighborhood', parentCity: 'netanya' },
    { id: 'netanya-kiryat-sapir', name: 'נתניה - קריית ספיר', category: 'neighborhood', parentCity: 'netanya' },
    { id: 'nof-hagilil', name: 'נוף הגליל (נצרת עילית)', category: 'city' },
    { id: 'nof-hagilil-har-yona', name: 'נוף הגליל - הר יונה ג\'', category: 'neighborhood', parentCity: 'nof-hagilil' },
    { id: 'nof-hagilil-ramat-golda', name: 'נוף הגליל - רמות גולדה מאיר', category: 'neighborhood', parentCity: 'nof-hagilil' },
    { id: 'nes-tziona', name: 'נס ציונה', category: 'city' },
    { id: 'nes-tziona-givat-michael', name: 'נס ציונה - גבעת מיכאל', category: 'neighborhood', parentCity: 'nes-tziona' },
    { id: 'nes-tziona-tirat-shalom', name: 'נס ציונה - טירת שלום', category: 'neighborhood', parentCity: 'nes-tziona' },
    { id: 'nes-tziona-kfar-aharon', name: 'נס ציונה - כפר אהרון', category: 'neighborhood', parentCity: 'nes-tziona' },
    { id: 'nir', name: 'ניר', category: 'city' },
    { id: 'asher', name: 'בן דור (שכונה)', category: 'neighborhood' },
    { id: 'givat-nir', name: 'גבעת נשר', category: 'neighborhood' },
    { id: 'ramat-isaac', name: 'רמות יצחק', category: 'neighborhood' },
    { id: 'tel-hanan', name: 'תל חנן', category: 'neighborhood' },
    { id: 'hertzelia', name: 'הרצליה', category: 'city' },
    { id: 'hertzelia-pituch', name: 'הרצליה - הרצליה פיתוח', category: 'neighborhood', parentCity: 'hertzelia' },
    { id: 'hertzelia-yad-hashisha', name: 'הרצליה - יד התשעה', category: 'neighborhood', parentCity: 'hertzelia' },
    { id: 'hertzelia-naveh-israel', name: 'הרצליה - נווה ישראל', category: 'neighborhood', parentCity: 'hertzelia' },
    { id: 'hertzelia-naveh-emel', name: 'הרצליה - נווה עמל', category: 'neighborhood', parentCity: 'hertzelia' },
    { id: 'hod-hasharon', name: 'הוד השרון', category: 'city' },
    { id: 'hod-hasharon-kfar-hadar', name: 'הוד השרון - כפר הדר', category: 'neighborhood', parentCity: 'hod-hasharon' },
    { id: 'hod-hasharon-naveh-naman', name: 'הוד השרון - נווה נאמן', category: 'neighborhood', parentCity: 'hod-hasharon' },
    { id: 'hod-hasharon-ramat-hadar', name: 'הוד השרון - רמת הדר', category: 'neighborhood', parentCity: 'hod-hasharon' },
    { id: 'hod-hasharon-ramatiim', name: 'הוד השרון - רמתיים', category: 'neighborhood', parentCity: 'hod-hasharon' },
    { id: 'ramat-gan', name: 'רמת גן', category: 'city' },
    { id: 'ramat-gan-shearim', name: 'רמת גן - שעריים', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-kfar-azr', name: 'רמת גן - כפר אז"ר', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-mrom-naveh', name: 'רמת גן - מרום נווה', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-kiryat-borokh', name: 'רמת גן - קריית בורוכוב', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-kiryat-krentski', name: 'רמת גן - קריית קריניצי', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-ramat-appel', name: 'רמת גן - רמת אפעל', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-ramat-amidar', name: 'רמת גן - רמת עמידר', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-tel-ganim', name: 'רמת גן - שכונת תל גנים', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-tel-binyamin', name: 'רמת גן - תל בנימין', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'ramat-gan-tel-hasomer', name: 'רמת גן - תל השומר', category: 'neighborhood', parentCity: 'ramat-gan' },
    { id: 'rahmat-hasharon', name: 'רמת השרון', category: 'city' },
    { id: 'ramat-hasharon-tzur-shalom', name: 'ראשון לציון - צור שלום', category: 'neighborhood' },
    { id: 'ramat-hasharon-nachalat-yehuda', name: 'ראשון לציון - נחלת יהודה', category: 'neighborhood' },
    { id: 'racheivot', name: 'רחובות', category: 'city' },
    { id: 'racheivot-ramez', name: 'רחובות - שכונת רמז', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-ushiyot', name: 'רחובות - אושיות', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-kfar-gabirol', name: 'רחובות - כפר גבירול', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-kfar-marmorek', name: 'רחובות - כפר מרמורק', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-park-tmr', name: 'רחובות - פארק ת.מ.ר', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-psagat-kretsnif', name: 'רחובות - פסגת קרעטשניף', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-kiryat-kretsnif', name: 'רחובות - קריית קרעטשניף', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-kiryat-vizhnitz', name: 'רחובות - קריית ויזניץ', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-kiryat-hagana', name: 'רחובות - קריית ההגנה', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-shikun-efraim', name: 'רחובות - שכונת אפרים', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'racheivot-shikun-habetzalet', name: 'רחובות - שכונת חבצלת', category: 'neighborhood', parentCity: 'racheivot' },
    { id: 'rishon-lezion', name: 'ראשון לציון', category: 'city' },
    { id: 'petach-tikva', name: 'פתח תקווה', category: 'city' },
    { id: 'petach-tikva-roavey-izreel', name: 'פתח תקווה - רובע יזרעאל', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-em-hamoshovot', name: 'פתח תקווה - אם המושבות', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-em-hamoshovot-new', name: 'פתח תקווה - אם המושבות החדשה', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-hadar-ganim-amisheb', name: 'פתח תקווה - הדר גנים-עמישב', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-kfar-avraham', name: 'פתח תקווה - כפר אברהם', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-kfar-ganim', name: 'פתח תקווה - כפר גנים', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-machaneh-yehuda', name: 'פתח תקווה - מחנה יהודה', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-naveh-gan', name: 'פתח תקווה - נווה גן', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-naveh-oz', name: 'פתח תקווה - נווה עוז', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-ein-ganim', name: 'פתח תקווה - עין גנים', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'petach-tikva-kiryat-metalon', name: 'פתח תקווה - קריית מטלון', category: 'neighborhood', parentCity: 'petach-tikva' },
    { id: 'afula', name: 'עפולה', category: 'city' },
    { id: 'afula-kiryat-tzanz', name: 'עפולה - קריית צאנז', category: 'neighborhood', parentCity: 'afula' },
    { id: 'afula-givat-hamora', name: 'עפולה - גבעת המורה', category: 'neighborhood', parentCity: 'afula' },
    { id: 'afula-elit', name: 'עפולה - עפולה עילית', category: 'neighborhood', parentCity: 'afula' },
    { id: 'tzfat', name: 'צפת', category: 'city' },
    { id: 'tzfat-ramat-varber', name: 'צפת - רמת ורבר', category: 'neighborhood', parentCity: 'tzfat' },
    { id: 'tzfat-old-city', name: 'צפת - צפת העתיקה', category: 'neighborhood', parentCity: 'tzfat' },
    { id: 'kiryat-bialik', name: 'קריית ביאליק', category: 'city' },
    { id: 'kiryat-bialik-akbara', name: 'קריית ביאליק - עכברה', category: 'neighborhood', parentCity: 'kiryat-bialik' },
    { id: 'kiryat-bialik-givat-harakfot', name: 'קריית ביאליק - גבעת הרקפות', category: 'neighborhood', parentCity: 'kiryat-bialik' },
    { id: 'kiryat-bialik-naot-apek', name: 'קריית ביאליק - נאות אפק', category: 'neighborhood', parentCity: 'kiryat-bialik' },
    { id: 'jerusalem', name: 'ירושלים', category: 'city' },
    // ירושלים - שכונות (רשימה מורחבת)
    { id: 'jerusalem-ator', name: 'ירושלים - א-טור', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-abu-tor', name: 'ירושלים - אבו תור', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-even-israel', name: 'ירושלים - אבן ישראל', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ahel-moshe', name: 'ירושלים - אהל משה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ohel-shlomo', name: 'ירושלים - אוהל שלמה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-al-amira', name: 'ירושלים - אל-אמירה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-arnona', name: 'ירושלים - ארנונה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-beit-orot', name: 'ירושלים - בית אורות', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-beit-david', name: 'ירושלים - בית דוד', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-beit-hakerem', name: 'ירושלים - בית הכרם', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-beit-vegan', name: 'ירושלים - בית וגן', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-beit-yosef', name: 'ירושלים - בית יוסף', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-beit-yaakov', name: 'ירושלים - בית יעקב', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-beit-israel', name: 'ירושלים - בית ישראל', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-bakaa', name: 'ירושלים - בקעה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-ungerin', name: 'ירושלים - בתי אונגרין', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-horodna', name: 'ירושלים - בתי הורודנא', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-hornstein', name: 'ירושלים - בתי הורנשטיין', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-veitenberg', name: 'ירושלים - בתי ויטנברג', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-varsha', name: 'ירושלים - בתי ורשה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-monkatz', name: 'ירושלים - בתי מונקאטש', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-minsk', name: 'ירושלים - בתי מינסק', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-neitin', name: 'ירושלים - בתי נייטין', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-nisan-bk', name: 'ירושלים - בתי ניסן ב"ק', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-rand', name: 'ירושלים - בתי ראנד', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-geula', name: 'ירושלים - גאולה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-ornit', name: 'ירושלים - גבעת אורנים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-hamavter', name: 'ירושלים - גבעת המבתר', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-hamatos', name: 'ירושלים - גבעת המטוס', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-hasaked', name: 'ירושלים - גבעת השקד', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-mordechai', name: 'ירושלים - גבעת מרדכי', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-moshe', name: 'ירושלים - גבעת משה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-mshoaa', name: 'ירושלים - גבעת משואה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-ram', name: 'ירושלים - גבעת רם', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-shaul', name: 'ירושלים - גבעת שאול', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-givat-shaul-b', name: 'ירושלים - גבעת שאול ב\'', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-gonanim', name: 'ירושלים - גוננים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-gilo', name: 'ירושלים - גילה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-hagiva-haturfanit', name: 'ירושלים - הגבעה הצרפתית', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-holland', name: 'ירושלים - הולילנד', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-german-colony', name: 'ירושלים - המושבה הגרמנית', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-greek-colony', name: 'ירושלים - המושבה היוונית', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-har-hatzofim', name: 'ירושלים - הר הצופים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-har-huma', name: 'ירושלים - הר חומה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-har-hotzvim', name: 'ירושלים - הר חוצבים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-har-nof', name: 'ירושלים - הר נוף', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-batei-verner', name: 'ירושלים - בתי ורנר', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-zichron-tuvia', name: 'ירושלים - זיכרון טוביה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-zichron-yosef', name: 'ירושלים - זיכרון יוסף', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-zichron-moshe', name: 'ירושלים - זיכרון משה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-chomat-shmuel', name: 'ירושלים - חומת שמואל', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-chatzer-shtraus', name: 'ירושלים - חצר שטרויס', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-talbia', name: 'ירושלים - טלביה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-yemin-moshe', name: 'ירושלים - ימין משה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-yafa-nof', name: 'ירושלים - יפה נוף', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kfar-hateimani', name: 'ירושלים - כפר התימנים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kerem-avraham', name: 'ירושלים - כרם אברהם', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mosrara', name: 'ירושלים - מוסררה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-motza', name: 'ירושלים - מוצא', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mezkeret-moshe', name: 'ירושלים - מזכרת משה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-machane-shufat', name: 'ירושלים - מחנה הפליטים שועפאט', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-machane-yehuda', name: 'ירושלים - מחנה יהודה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-machane-israel', name: 'ירושלים - מחנה ישראל', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-machanayim', name: 'ירושלים - מחניים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-malha', name: 'ירושלים - מלחה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mamila', name: 'ירושלים - ממילא', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mealet-hazeitim', name: 'ירושלים - מעלה הזיתים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mealot-dafna', name: 'ירושלים - מעלות דפנה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mekor-baruch', name: 'ירושלים - מקור ברוך', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mekor-hayim', name: 'ירושלים - מקור חיים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-marhabiyya', name: 'ירושלים - מרחביה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mishkenot-israel', name: 'ירושלים - משכנות ישראל', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-mishkenot-shananim', name: 'ירושלים - משכנות שאננים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-naveh-granot', name: 'ירושלים - נווה גרנות', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-naveh-yaakov', name: 'ירושלים - נווה יעקב', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-naveh-shanan', name: 'ירושלים - נווה שאנן', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-nof-tzion', name: 'ירושלים - נוף ציון', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-nachalt-achim', name: 'ירושלים - נחלת אחים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-nachlat-tzvi', name: 'ירושלים - נחלת צבי', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-nachlat-zadok', name: 'ירושלים - נחלת צדוק', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-nachlat-shiva', name: 'ירושלים - נחלת שבעה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-nachlat-shmeon', name: 'ירושלים - נחלת שמעון', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-niyot', name: 'ירושלים - ניות', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-sukkat-shalom', name: 'ירושלים - סוכת שלום', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-silwan', name: 'ירושלים - סילואן', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-sanhedria', name: 'ירושלים - סנהדריה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-sanhedria-expanded', name: 'ירושלים - סנהדריה המורחבת', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-azrat-israel', name: 'ירושלים - עזרת ישראל', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-azrat-torah', name: 'ירושלים - עזרת תורה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ein-kerem', name: 'ירושלים - עין כרם', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ir-ganim', name: 'ירושלים - עיר גנים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-etz-hayim', name: 'ירושלים - עץ חיים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-psgat-zaev', name: 'ירושלים - פסגת זאב', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-pat', name: 'ירושלים - פת', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-tzur-baher', name: 'ירושלים - צור באהר', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-tzimrat-habira', name: 'ירושלים - צמרת הבירה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kadmat-tzion', name: 'ירושלים - קדמת ציון', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-katamon', name: 'ירושלים - קטמון', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-onsdorf', name: 'ירושלים - קריית אונסדורף', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-baelz', name: 'ירושלים - קריית בעלז', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-hayovel', name: 'ירושלים - קריית היובל', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-haleum', name: 'ירושלים - קריית הלאום', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-hamemshala', name: 'ירושלים - קריית הממשלה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-hamemshala-east', name: 'ירושלים - קריית הממשלה (מזרח)', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-wolfson', name: 'ירושלים - קריית וולפסון', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-matersdorf', name: 'ירושלים - קריית מטרסדורף', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-menachem', name: 'ירושלים - קריית מנחם', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-moshe', name: 'ירושלים - קריית משה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-tzanz', name: 'ירושלים - קריית צאנז', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-shomrei-emunim', name: 'ירושלים - קריית שומרי אמונים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-kiryat-shmuel', name: 'ירושלים - קריית שמואל', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ras-al-amud', name: 'ירושלים - ראס אל-עמוד', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-romena', name: 'ירושלים - רוממה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-rehavia', name: 'ירושלים - רחביה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ramot-alon', name: 'ירושלים - רמות אלון', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ramot-polin', name: 'ירושלים - רמות פולין', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ramat-ashkol', name: 'ירושלים - רמת אשכול', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ramat-beit-hakerem', name: 'ירושלים - רמת בית הכרם', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ramat-dania', name: 'ירושלים - רמת דניה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ramat-shlomo', name: 'ירושלים - רמת שלמה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-ramat-seret', name: 'ירושלים - רמת שרת', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-rasko', name: 'ירושלים - רסקו', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shikun-harabbanim', name: 'ירושלים - שיכון הרבנים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shikun-chabad', name: 'ירושלים - שיכון חב"ד', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shikun-pagi', name: 'ירושלים - שיכון פאג"י', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shikun-ahava', name: 'ירושלים - שכונת אחווה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shikun-emmat-hamayim', name: 'ירושלים - שכונת אמת המים התחתונה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shikun-bocharim', name: 'ירושלים - שכונת הבוכרים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shikun-haPoelim', name: 'ירושלים - שכונת הפועלים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shikun-shmeon-hatzadik', name: 'ירושלים - שכונת שמעון הצדיק', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shmuel-hanavi', name: 'ירושלים - שמואל הנביא', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shaarei-hesed', name: 'ירושלים - שערי חסד', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shaarei-yerushalayim', name: 'ירושלים - שערי ירושלים', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-shaarei-tzedek', name: 'ירושלים - שערי צדק', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-tel-arzah', name: 'ירושלים - תל ארזה', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-talpiot', name: 'ירושלים - תלפיות', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'jerusalem-talpiot-east', name: 'ירושלים - תלפיות מזרח', category: 'neighborhood', parentCity: 'jerusalem' },
    { id: 'tel-aviv-jaffa', name: 'תל אביב יפו', category: 'city' },
    // תל אביב יפו - שכונות (רשימה מורחבת)
    { id: 'tel-aviv-abu-kibir', name: 'תל אביב - אבו כביר', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-ohel-moshe', name: 'תל אביב - אוהל משה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-ofek-hayam', name: 'תל אביב - אופק הים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-orot', name: 'תל אביב - אורות', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-zone-industry', name: 'תל אביב - אזור תעשייה עבר הירקון', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-azor-chen', name: 'תל אביב - אזורי חן', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-afeka', name: 'תל אביב - אפקה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-bitzaron', name: 'תל אביב - ביצרון', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-givat-herzel', name: 'תל אביב - גבעת הרצל', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-givat-alikah', name: 'תל אביב - גבעת עלייה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-givat-emel', name: 'תל אביב - גבעת עמל ב\'', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-hamistala', name: 'תל אביב - המשתלה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-hatzzafon-hadash', name: 'תל אביב - הצפון החדש', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-hatzafon-hayashan', name: 'תל אביב - הצפון הישן', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-hakerayah', name: 'תל אביב - הקריה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-yad-eliyahu', name: 'תל אביב - יד אליהו', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-yafo-gimel', name: 'תל אביב - יפו ג\'', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-yafo-dalet', name: 'תל אביב - יפו ד\'', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-yishgav', name: 'תל אביב - ישגב', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kokhav-hatzafon', name: 'תל אביב - כוכב הצפון', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kfar-shalom', name: 'תל אביב - כפר שלם', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kerem-hateimani', name: 'תל אביב - כרם התימנים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kerem-israel', name: 'תל אביב - כרם ישראל', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kerem-moshe', name: 'תל אביב - כרם משה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-lev', name: 'תל אביב - לב תל אביב', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-meah-shearim', name: 'תל אביב - מאה שערים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-migdalei-naaman', name: 'תל אביב - מגדלי נאמן', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-makhlol', name: 'תל אביב - שכונת מחלול', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-machane-yehuda', name: 'תל אביב - מחנה יהודה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-machane-yosef', name: 'תל אביב - מחנה יוסף', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-manshia', name: 'תל אביב - מנשייה (יפו)', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-maoz-aviv', name: 'תל אביב - מעוז אביב', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-merkaz-baalei-mlaha', name: 'תל אביב - מרכז בעלי מלאכה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-merkaz-merchanit', name: 'תל אביב - מרכז מסחרי', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-matcam-ludovipol', name: 'תל אביב - מתחם לודוויפול', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naot-afeka', name: 'תל אביב - נאות אפקה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-avivim', name: 'תל אביב - נווה אביבים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-aliezer', name: 'תל אביב - נווה אליעזר', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-barburim', name: 'תל אביב - נווה ברבור', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-chen', name: 'תל אביב - נווה חן', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-kafir', name: 'תל אביב - נווה כפיר', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-ofer', name: 'תל אביב - נווה עופר', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-tzedek', name: 'תל אביב - נווה צדק', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-tzahal', name: 'תל אביב - נווה צה"ל', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-shanan', name: 'תל אביב - נווה שאנן', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-shalom', name: 'תל אביב - נווה שלום', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-naveh-seret', name: 'תל אביב - נווה שרת', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-nofei-yam', name: 'תל אביב - נופי ים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-nordia', name: 'תל אביב - נורדיה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-nachlat-binyamin', name: 'תל אביב - נחלת בנימין', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-nachlat-yitzhak-east', name: 'תל אביב - נחלת יצחק (מזרח)', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-nachlat-yitzhak-center', name: 'תל אביב - נחלת יצחק (מרכז)', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-park-tzimrat', name: 'תל אביב - פארק צמרת', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-florentin', name: 'תל אביב - פלורנטין', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-pnei-afik', name: 'תל אביב - שכונת פקידי אפ"ק', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-pardes-daka', name: 'תל אביב - פרדס דכה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-zahala', name: 'תל אביב - צהלה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-zahalon', name: 'תל אביב - צהלון', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-tzuki-aviv', name: 'תל אביב - צוקי אביב', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kiryat-hamlaha', name: 'תל אביב - קריית המלאכה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kiryat-meir', name: 'תל אביב - קריית מאיר', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kiryat-shaul', name: 'תל אביב - קריית שאול', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-kiryat-shalom', name: 'תל אביב - קריית שלום', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-ramat-aviv', name: 'תל אביב - רמת אביב', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-ramat-aviv-gimel', name: 'תל אביב - רמת אביב ג\'', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-ramat-hachayil', name: 'תל אביב - רמת החייל', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-ramat-hatayasim', name: 'תל אביב - רמת הטייסים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-ramat-hasharon', name: 'תל אביב - רמת השרון', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-ramat-israel', name: 'תל אביב - רמת ישראל', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-balti', name: 'תל אביב - שיכון בבלי', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-dan', name: 'תל אביב - שיכון דן', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-tzimrat', name: 'תל אביב - שיכון צמרת', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-chisachon', name: 'תל אביב - שיכוני חיסכון', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-ever-hirkoun', name: 'תל אביב - שכונות עבר הירקון', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-ahava', name: 'תל אביב - שכונת אחווה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-hargazi', name: 'תל אביב - שכונת הארגזים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-hatikva', name: 'תל אביב - שכונת התקווה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-yadidya', name: 'תל אביב - שכונת ידידיה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-lamad', name: 'תל אביב - שכונת למד', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-montifiori', name: 'תל אביב - שכונת מונטיפיורי', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-ezra', name: 'תל אביב - שכונת עזרא', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-ravivim', name: 'תל אביב - שכונת רביבים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-shabazi', name: 'תל אביב - שכונת שבזי', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-shapak', name: 'תל אביב - שכונת שפאק', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-shikun-shapira', name: 'תל אביב - שכונת שפירא', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-sharona', name: 'תל אביב - שרונה', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-tel-bruoch', name: 'תל אביב - תל ברוך', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-tel-hayim', name: 'תל אביב - תל חיים', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },
    { id: 'tel-aviv-tel-nordau', name: 'תל אביב - תל נורדאו', category: 'neighborhood', parentCity: 'tel-aviv-jaffa' },

    // שאר הערים בישראל (בקצרה)
    { id: 'eilat', name: 'אילת', category: 'city' },
    { id: 'rehovot', name: 'רחובות', category: 'city' },
    { id: 'ramlah', name: 'רמלה', category: 'city' },
    { id: 'lachish', name: 'לכיש', category: 'city' },
    { id: 'maalot-tarshicha', name: 'מעלות-תרשיחא', category: 'city' },
    { id: 'nahariyya', name: 'נהריה', category: 'city' },
    { id: 'kiryat-shmona', name: 'קריית שמונה', category: 'city' },
    { id: 'sakhnin', name: 'סכנין', category: 'city' },
    { id: 'sderot', name: 'שדרות', category: 'city' },
    { id: 'dimona', name: 'דימונה', category: 'city' },
    { id: 'mitzpe-ramon', name: 'מצפה רמון', category: 'city' },
    { id: 'arad', name: 'ערד', category: 'city' },
    { id: 'netivot', name: 'נתיבות', category: 'city' },
    { id: 'yeruham', name: 'ירוחם', category: 'city' },
    { id: 'baka-al-garbiyeh', name: 'בקה אל-גרביה', category: 'city' },
    { id: 'umm-al-fahm', name: 'אום אל-פחם', category: 'city' },
    { id: 'qalanswa', name: 'קלנסווה', category: 'city' },
    { id: 'jatt', name: 'ג\'ת', category: 'city' },
    { id: 'tayibe', name: 'טיבה', category: 'city' },
    { id: 'kafr-qasem', name: 'כפר קאסם', category: 'city' },
    { id: 'ramallah', name: 'רמאללה', category: 'city' },
    { id: 'bethlehem', name: 'בית לחם', category: 'city' },
    { id: 'hebron', name: 'חברון', category: 'city' },
];

export function getCityById(id: string): City | undefined {
    return cities.find(city => city.id === id);
}

export function getCitiesByParent(parentId: string): City[] {
    return cities.filter(city => city.parentCity === parentId);
}

export function getAllCities(): City[] {
    return cities.filter(city => city.category === 'city');
}

export function getAllNeighborhoods(): City[] {
    return cities.filter(city => city.category === 'neighborhood');
}

export function searchCities(query: string): City[] {
    const lowerQuery = query.toLowerCase();
    return cities.filter(city => city.name.toLowerCase().includes(lowerQuery));
}
