// Single source of truth for all cities and neighborhoods.
// Add a new city/neighborhood here and it will automatically
// appear everywhere in the app (advertise page, map, home page).

export interface CityEntry {
    city: string;
    neighborhoods: string[];
}

// יישובים בודדים ללא שכונות מוגדרות — כברירת מחדל "מרכז"
const DEFAULT_NB = ["מרכז"];

export const citiesData: CityEntry[] = [
    // ============== א ==============
    { city: "אבטליון", neighborhoods: DEFAULT_NB },
    { city: "אביאל", neighborhoods: DEFAULT_NB },
    { city: "אביבים", neighborhoods: DEFAULT_NB },
    { city: "אביגדור", neighborhoods: DEFAULT_NB },
    { city: "אביחיל", neighborhoods: DEFAULT_NB },
    { city: "אביטל", neighborhoods: DEFAULT_NB },
    { city: "אביעזר", neighborhoods: DEFAULT_NB },
    { city: "אבירים", neighborhoods: DEFAULT_NB },
    { city: "אבן יהודה", neighborhoods: DEFAULT_NB },
    { city: "אבן מנחם", neighborhoods: DEFAULT_NB },
    { city: "אבן ספיר", neighborhoods: DEFAULT_NB },
    { city: "אבן שמואל", neighborhoods: DEFAULT_NB },
    { city: "אבני איתן", neighborhoods: DEFAULT_NB },
    { city: "אבני חפץ", neighborhoods: DEFAULT_NB },
    { city: "אבנת", neighborhoods: DEFAULT_NB },
    { city: "אבשלום", neighborhoods: DEFAULT_NB },
    { city: "אדורה", neighborhoods: DEFAULT_NB },
    { city: "אדירים", neighborhoods: DEFAULT_NB },
    { city: "אדמית", neighborhoods: DEFAULT_NB },
    { city: "אדרת", neighborhoods: DEFAULT_NB },
    { city: "אודים", neighborhoods: DEFAULT_NB },
    { city: "אודם", neighborhoods: DEFAULT_NB },
    { city: "אוהד", neighborhoods: DEFAULT_NB },
    { city: "אומן", neighborhoods: DEFAULT_NB },
    { city: "אומץ", neighborhoods: DEFAULT_NB },
    { city: "אופקים", neighborhoods: ["מרכז העיר", "שכונה א", "שכונה ב"] },
    { city: "אור הגנוז", neighborhoods: DEFAULT_NB },
    { city: "אור הנר", neighborhoods: DEFAULT_NB },
    { city: "אור יהודה", neighborhoods: ["מרכז", "נווה אפריים", "קרית אונו הצעירה"] },
    { city: "אור עקיבא", neighborhoods: ["מרכז העיר", "שכונת הגפן"] },
    { city: "אורה", neighborhoods: DEFAULT_NB },
    { city: "אורות", neighborhoods: DEFAULT_NB },
    { city: "אורטל", neighborhoods: DEFAULT_NB },
    { city: "אורים", neighborhoods: DEFAULT_NB },
    { city: "אורנים", neighborhoods: DEFAULT_NB },
    { city: "אורנית", neighborhoods: DEFAULT_NB },
    { city: "אושה", neighborhoods: DEFAULT_NB },
    { city: "אזור", neighborhoods: DEFAULT_NB },
    { city: "אחווה", neighborhoods: DEFAULT_NB },
    { city: "אחוזם", neighborhoods: DEFAULT_NB },
    { city: "אחוזת ברק", neighborhoods: DEFAULT_NB },
    { city: "אחיהוד", neighborhoods: DEFAULT_NB },
    { city: "אחיטוב", neighborhoods: DEFAULT_NB },
    { city: "אחיסמך", neighborhoods: DEFAULT_NB },
    { city: "אחיעזר", neighborhoods: DEFAULT_NB },
    { city: "איבים", neighborhoods: DEFAULT_NB },
    { city: "אייל", neighborhoods: DEFAULT_NB },
    { city: "איילת השחר", neighborhoods: DEFAULT_NB },
    { city: "אילון", neighborhoods: DEFAULT_NB },
    { city: "אילות", neighborhoods: DEFAULT_NB },
    { city: "אילניה", neighborhoods: DEFAULT_NB },
    { city: "אילת", neighborhoods: ["שכונת התמרים", "שכונת הדקלים", "שכונת השחמון", "נאות אילות"] },
    { city: "אירוס", neighborhoods: DEFAULT_NB },
    { city: "איתן", neighborhoods: DEFAULT_NB },
    { city: "איתנים", neighborhoods: DEFAULT_NB },
    { city: "אלומה", neighborhoods: DEFAULT_NB },
    { city: "אלומות", neighborhoods: DEFAULT_NB },
    { city: "אלון הגליל", neighborhoods: DEFAULT_NB },
    { city: "אלוני אבא", neighborhoods: DEFAULT_NB },
    { city: "אלוני הבשן", neighborhoods: DEFAULT_NB },
    { city: "אלוני יצחק", neighborhoods: DEFAULT_NB },
    { city: "אלונים", neighborhoods: DEFAULT_NB },
    { city: "אלי-עד", neighborhoods: DEFAULT_NB },
    { city: "אליאב", neighborhoods: DEFAULT_NB },
    { city: "אליכין", neighborhoods: DEFAULT_NB },
    { city: "אליפז", neighborhoods: DEFAULT_NB },
    { city: "אליפלט", neighborhoods: DEFAULT_NB },
    { city: "אליקים", neighborhoods: DEFAULT_NB },
    { city: "אלישיב", neighborhoods: DEFAULT_NB },
    { city: "אלישמע", neighborhoods: DEFAULT_NB },
    { city: "אלמגור", neighborhoods: DEFAULT_NB },
    { city: "אלעד", neighborhoods: ["מרכז", "שכונת הרב קוק"] },
    { city: "אלקוש", neighborhoods: DEFAULT_NB },
    { city: "אמונים", neighborhoods: DEFAULT_NB },
    { city: "אמירים", neighborhoods: DEFAULT_NB },
    { city: "אמנון", neighborhoods: DEFAULT_NB },
    { city: "אמציה", neighborhoods: DEFAULT_NB },
    { city: "אניעם", neighborhoods: DEFAULT_NB },
    { city: "אפיק", neighborhoods: DEFAULT_NB },
    { city: "אפיקים", neighborhoods: DEFAULT_NB },
    { city: "אפק", neighborhoods: DEFAULT_NB },
    { city: "ארבל", neighborhoods: DEFAULT_NB },
    { city: "ארז", neighborhoods: DEFAULT_NB },
    { city: "ארסוף", neighborhoods: DEFAULT_NB },
    { city: "אשבול", neighborhoods: DEFAULT_NB },
    { city: "אשבל", neighborhoods: DEFAULT_NB },
    { city: "אשדוד", neighborhoods: ["רובע א", "רובע ב", "רובע ג", "רובע ד", "רובע ה", "רובע ו", "רובע ז", "רובע ח", "צפון", "עיר ימים"] },
    { city: "אשדות יעקב (איחוד)", neighborhoods: DEFAULT_NB },
    { city: "אשדות יעקב (מאוחד)", neighborhoods: DEFAULT_NB },
    { city: "אשחר", neighborhoods: DEFAULT_NB },
    { city: "אשל הנשיא", neighborhoods: DEFAULT_NB },
    { city: "אשלים", neighborhoods: DEFAULT_NB },
    { city: "אשקלון", neighborhoods: ["שכונת אפרידר", "שכונת שמשון", "ברנע", "גיורא", "הנשיא", "עזתה"] },
    { city: "אשרת", neighborhoods: DEFAULT_NB },
    { city: "אשתאול", neighborhoods: DEFAULT_NB },
    { city: "אתגר", neighborhoods: DEFAULT_NB },

    // ============== ב ==============
    { city: "באר אורה", neighborhoods: DEFAULT_NB },
    { city: "באר גנים", neighborhoods: DEFAULT_NB },
    { city: "באר טוביה", neighborhoods: DEFAULT_NB },
    { city: "באר יעקב", neighborhoods: DEFAULT_NB },
    { city: "באר מילכה", neighborhoods: DEFAULT_NB },
    { city: "באר שבע", neighborhoods: ["העיר העתיקה", "שכונת דרום", "הדאון טאון (המרכז האזרחי)", "שכונה א'", "שכונה ב'", "שכונה ג'", "שכונה ד'", "שכונה ה'", "שכונה ו'", "שכונה ט'", "שכונה י\"א", "נאות לון", "נווה זאב", "נווה נוי", "נחל בקע", "נחל עשן (נווה מנחם)", "שכונת הסיגליות", "רמות", "נאות אברהם", "נווה אילן (פלח 7)", "שכונת קריית גנים", "שכונת הכלניות"] },
    { city: "בארות יצחק", neighborhoods: DEFAULT_NB },
    { city: "בארותיים", neighborhoods: DEFAULT_NB },
    { city: "בארי", neighborhoods: DEFAULT_NB },
    { city: "בוסתן הגליל", neighborhoods: DEFAULT_NB },
    { city: "בחן", neighborhoods: DEFAULT_NB },
    { city: "בטחה", neighborhoods: DEFAULT_NB },
    { city: "ביצרון", neighborhoods: DEFAULT_NB },
    { city: "ביר אל-מכסור", neighborhoods: DEFAULT_NB },
    { city: "ביריה", neighborhoods: DEFAULT_NB },
    { city: "בית אורן", neighborhoods: DEFAULT_NB },
    { city: "בית אלעזרי", neighborhoods: DEFAULT_NB },
    { city: "בית אלפא", neighborhoods: DEFAULT_NB },
    { city: "בית ברל", neighborhoods: DEFAULT_NB },
    { city: "בית גוברין", neighborhoods: DEFAULT_NB },
    { city: "בית גמליאל", neighborhoods: DEFAULT_NB },
    { city: "בית דגן", neighborhoods: DEFAULT_NB },
    { city: "בית הגדי", neighborhoods: DEFAULT_NB },
    { city: "בית הלוי", neighborhoods: DEFAULT_NB },
    { city: "בית הלל", neighborhoods: DEFAULT_NB },
    { city: "בית העמק", neighborhoods: DEFAULT_NB },
    { city: "בית השיטה", neighborhoods: DEFAULT_NB },
    { city: "בית זית", neighborhoods: DEFAULT_NB },
    { city: "בית זרע", neighborhoods: DEFAULT_NB },
    { city: "בית חירות", neighborhoods: DEFAULT_NB },
    { city: "בית חלקיה", neighborhoods: DEFAULT_NB },
    { city: "בית חנן", neighborhoods: DEFAULT_NB },
    { city: "בית חנניה", neighborhoods: DEFAULT_NB },
    { city: "בית חשמונאי", neighborhoods: DEFAULT_NB },
    { city: "בית יהושע", neighborhoods: DEFAULT_NB },
    { city: "בית יוסף", neighborhoods: DEFAULT_NB },
    { city: "בית ינאי", neighborhoods: DEFAULT_NB },
    { city: "בית יצחק-שער חפר", neighborhoods: DEFAULT_NB },
    { city: "בית לחם הגלילית", neighborhoods: DEFAULT_NB },
    { city: "בית מאיר", neighborhoods: DEFAULT_NB },
    { city: "בית נחמיה", neighborhoods: DEFAULT_NB },
    { city: "בית ניר", neighborhoods: DEFAULT_NB },
    { city: "בית נקופה", neighborhoods: DEFAULT_NB },
    { city: "בית עובד", neighborhoods: DEFAULT_NB },
    { city: "בית עוזיאל", neighborhoods: DEFAULT_NB },
    { city: "בית עזרא", neighborhoods: DEFAULT_NB },
    { city: "בית צבי", neighborhoods: DEFAULT_NB },
    { city: "בית קמה", neighborhoods: DEFAULT_NB },
    { city: "בית קשת", neighborhoods: DEFAULT_NB },
    { city: "בית רבן", neighborhoods: DEFAULT_NB },
    { city: "בית רימון", neighborhoods: DEFAULT_NB },
    { city: "בית שאן", neighborhoods: ["מרכז", "קרית נחמה", "שכונה ב"] },
    { city: "בית שמש", neighborhoods: ["בית שמש א", "בית שמש ב", "בית שמש ג", "רמת בית שמש א", "רמת בית שמש ב"] },
    { city: "בית שערים", neighborhoods: DEFAULT_NB },
    { city: "בית שקמה", neighborhoods: DEFAULT_NB },
    { city: "ביתן אהרן", neighborhoods: DEFAULT_NB },
    { city: "בלפוריה", neighborhoods: DEFAULT_NB },
    { city: "בן זכאי", neighborhoods: DEFAULT_NB },
    { city: "בן עמי", neighborhoods: DEFAULT_NB },
    { city: "בן שמן (כפר נוער)", neighborhoods: DEFAULT_NB },
    { city: "בן שמן (מושב)", neighborhoods: DEFAULT_NB },
    { city: "בני ברק", neighborhoods: ["אור החיים", "גבעת רוקח", "גני גד", "הר שלום", "זכרון מאיר", "נוה אחיעזר", "פרדס כץ", "קריית הרצוג", "קריית ויז'ניץ", "קריית נדבורנה", "רמת אהרן", "רמת אלחנן", "שיכון ה'", "שיכון ההסתדרות", "שיכון ו'", "שיכון חזון איש", "תל גיבורים"] },
    { city: "בני דקלים", neighborhoods: DEFAULT_NB },
    { city: "בני דרום", neighborhoods: DEFAULT_NB },
    { city: "בני דרור", neighborhoods: DEFAULT_NB },
    { city: "בני יהודה", neighborhoods: DEFAULT_NB },
    { city: "בני נצרים", neighborhoods: DEFAULT_NB },
    { city: "בני עטרות", neighborhoods: DEFAULT_NB },
    { city: "בני עי\"ש", neighborhoods: DEFAULT_NB },
    { city: "בני ציון", neighborhoods: DEFAULT_NB },
    { city: "בני ראם", neighborhoods: DEFAULT_NB },
    { city: "בניה", neighborhoods: DEFAULT_NB },
    { city: "בנימינה-גבעת עדה", neighborhoods: DEFAULT_NB },
    { city: "בסמת טבעון", neighborhoods: DEFAULT_NB },
    { city: "בצרה", neighborhoods: DEFAULT_NB },
    { city: "בצת", neighborhoods: DEFAULT_NB },
    { city: "בקוע", neighborhoods: DEFAULT_NB },
    { city: "בר גיורא", neighborhoods: DEFAULT_NB },
    { city: "בר יוחאי", neighborhoods: DEFAULT_NB },
    { city: "ברור חיל", neighborhoods: DEFAULT_NB },
    { city: "ברוש", neighborhoods: DEFAULT_NB },
    { city: "ברכה", neighborhoods: DEFAULT_NB },
    { city: "ברכיה", neighborhoods: DEFAULT_NB },
    { city: "ברעם", neighborhoods: DEFAULT_NB },
    { city: "ברק", neighborhoods: DEFAULT_NB },
    { city: "ברקאי", neighborhoods: DEFAULT_NB },
    { city: "ברקת", neighborhoods: DEFAULT_NB },
    { city: "בת הדר", neighborhoods: DEFAULT_NB },
    { city: "בת חן", neighborhoods: DEFAULT_NB },
    { city: "בת חפר", neighborhoods: DEFAULT_NB },
    { city: "בת ים", neighborhoods: ["מרכז", "רמת יוסף", "קריית באבוב"] },
    { city: "בת שלמה", neighborhoods: DEFAULT_NB },

    // ============== ג ==============
    { city: "גאולי תימן", neighborhoods: DEFAULT_NB },
    { city: "גאולים", neighborhoods: DEFAULT_NB },
    { city: "גאליה", neighborhoods: DEFAULT_NB },
    { city: "גבולות", neighborhoods: DEFAULT_NB },
    { city: "גבים", neighborhoods: DEFAULT_NB },
    { city: "גבע", neighborhoods: DEFAULT_NB },
    { city: "גבע כרמל", neighborhoods: DEFAULT_NB },
    { city: "גבעולים", neighborhoods: DEFAULT_NB },
    { city: "גבעות הרואה", neighborhoods: DEFAULT_NB },
    { city: "גבעות עדן", neighborhoods: DEFAULT_NB },
    { city: "גבעת אבני", neighborhoods: DEFAULT_NB },
    { city: "גבעת אלה", neighborhoods: DEFAULT_NB },
    { city: "גבעת ברנר", neighborhoods: DEFAULT_NB },
    { city: "גבעת השלושה", neighborhoods: DEFAULT_NB },
    { city: "גבעת ח\"ן", neighborhoods: DEFAULT_NB },
    { city: "גבעת חיים (איחוד)", neighborhoods: DEFAULT_NB },
    { city: "גבעת חיים (מאוחד)", neighborhoods: DEFAULT_NB },
    { city: "גבעת יואב", neighborhoods: DEFAULT_NB },
    { city: "גבעת יערים", neighborhoods: DEFAULT_NB },
    { city: "גבעת ישעיהו", neighborhoods: DEFAULT_NB },
    { city: "גבעת כ\"ח", neighborhoods: DEFAULT_NB },
    { city: "גבעת ניל\"י", neighborhoods: DEFAULT_NB },
    { city: "גבעת עוז", neighborhoods: DEFAULT_NB },
    { city: "גבעת שמואל", neighborhoods: ["מרכז", "גבעת הגפן", "נאות רמז"] },
    { city: "גבעת שמש", neighborhoods: DEFAULT_NB },
    { city: "גבעת שפירא", neighborhoods: DEFAULT_NB },
    { city: "גבעתי", neighborhoods: DEFAULT_NB },
    { city: "גבעתיים", neighborhoods: ["בורוכוב", "כצנלסון", "קרית יוסף", "רמת יוסף"] },
    { city: "גברעם", neighborhoods: DEFAULT_NB },
    { city: "גבת", neighborhoods: DEFAULT_NB },
    { city: "גדות", neighborhoods: DEFAULT_NB },
    { city: "גדיש", neighborhoods: DEFAULT_NB },
    { city: "גדעונה", neighborhoods: DEFAULT_NB },
    { city: "גדרה", neighborhoods: ["מרכז", "שכונת הגן", "גן הדרים"] },
    { city: "גונן", neighborhoods: DEFAULT_NB },
    { city: "גורן", neighborhoods: DEFAULT_NB },
    { city: "גורנות הגליל", neighborhoods: DEFAULT_NB },
    { city: "גזית", neighborhoods: DEFAULT_NB },
    { city: "גזר", neighborhoods: DEFAULT_NB },
    { city: "גיאה", neighborhoods: DEFAULT_NB },
    { city: "גילון", neighborhoods: DEFAULT_NB },
    { city: "גילת", neighborhoods: DEFAULT_NB },
    { city: "גינוסר", neighborhoods: DEFAULT_NB },
    { city: "גיניגר", neighborhoods: DEFAULT_NB },
    { city: "גינתון", neighborhoods: DEFAULT_NB },
    { city: "גיתה", neighborhoods: DEFAULT_NB },
    { city: "גלאון", neighborhoods: DEFAULT_NB },
    { city: "גליל ים", neighborhoods: DEFAULT_NB },
    { city: "גלעד (אבן יצחק)", neighborhoods: DEFAULT_NB },
    { city: "גמזו", neighborhoods: DEFAULT_NB },
    { city: "גן הדרום", neighborhoods: DEFAULT_NB },
    { city: "גן השומרון", neighborhoods: DEFAULT_NB },
    { city: "גן חיים", neighborhoods: DEFAULT_NB },
    { city: "גן יאשיה", neighborhoods: DEFAULT_NB },
    { city: "גן יבנה", neighborhoods: DEFAULT_NB },
    { city: "גן נר", neighborhoods: DEFAULT_NB },
    { city: "גן שורק", neighborhoods: DEFAULT_NB },
    { city: "גן שלמה", neighborhoods: DEFAULT_NB },
    { city: "גן שמואל", neighborhoods: DEFAULT_NB },
    { city: "גנות", neighborhoods: DEFAULT_NB },
    { city: "גנות הדר", neighborhoods: DEFAULT_NB },
    { city: "גני הדר", neighborhoods: DEFAULT_NB },
    { city: "גני טל", neighborhoods: DEFAULT_NB },
    { city: "גני יוחנן", neighborhoods: DEFAULT_NB },
    { city: "גני עם", neighborhoods: DEFAULT_NB },
    { city: "גני תקווה", neighborhoods: DEFAULT_NB },
    { city: "געש", neighborhoods: DEFAULT_NB },
    { city: "געתון", neighborhoods: DEFAULT_NB },
    { city: "גפן", neighborhoods: DEFAULT_NB },
    { city: "גרופית", neighborhoods: DEFAULT_NB },
    { city: "גשור", neighborhoods: DEFAULT_NB },
    { city: "גשר", neighborhoods: DEFAULT_NB },
    { city: "גשר הזיו", neighborhoods: DEFAULT_NB },
    { city: "גת (קיבוץ)", neighborhoods: DEFAULT_NB },
    { city: "גת רימון", neighborhoods: DEFAULT_NB },

    // ============== ד ==============
    { city: "דבורה", neighborhoods: DEFAULT_NB },
    { city: "דביר", neighborhoods: DEFAULT_NB },
    { city: "דברת", neighborhoods: DEFAULT_NB },
    { city: "דגניה א'", neighborhoods: DEFAULT_NB },
    { city: "דגניה ב'", neighborhoods: DEFAULT_NB },
    { city: "דוב\"ב", neighborhoods: DEFAULT_NB },
    { city: "דור", neighborhoods: DEFAULT_NB },
    { city: "דורות", neighborhoods: DEFAULT_NB },
    { city: "דחי", neighborhoods: DEFAULT_NB },
    { city: "דימונה", neighborhoods: ["מרכז", "שכונת כלנית", "שכונת נרקיס"] },
    { city: "דישון", neighborhoods: DEFAULT_NB },
    { city: "דליה", neighborhoods: DEFAULT_NB },
    { city: "דלתון", neighborhoods: DEFAULT_NB },
    { city: "דן", neighborhoods: DEFAULT_NB },
    { city: "דפנה", neighborhoods: DEFAULT_NB },
    { city: "דקל", neighborhoods: DEFAULT_NB },

    // ============== ה ==============
    { city: "האון", neighborhoods: DEFAULT_NB },
    { city: "הבונים", neighborhoods: DEFAULT_NB },
    { city: "הגושרים", neighborhoods: DEFAULT_NB },
    { city: "הדר עם", neighborhoods: DEFAULT_NB },
    { city: "הוד השרון", neighborhoods: ["מרכז", "כפר הדר", "נווה נאמן", "רמת הדר", "רמתיים", "גנות", "צהלה", "שכונת אורנים"] },
    { city: "הודיה", neighborhoods: DEFAULT_NB },
    { city: "הודיות", neighborhoods: DEFAULT_NB },
    { city: "הושעיה", neighborhoods: DEFAULT_NB },
    { city: "הזורע", neighborhoods: DEFAULT_NB },
    { city: "הזורעים", neighborhoods: DEFAULT_NB },
    { city: "החותרים", neighborhoods: DEFAULT_NB },
    { city: "היוגב", neighborhoods: DEFAULT_NB },
    { city: "הילה", neighborhoods: DEFAULT_NB },
    { city: "המעפיל", neighborhoods: DEFAULT_NB },
    { city: "הסוללים", neighborhoods: DEFAULT_NB },
    { city: "העוגן", neighborhoods: DEFAULT_NB },
    { city: "הר גילה", neighborhoods: DEFAULT_NB },
    { city: "הר עמשא", neighborhoods: DEFAULT_NB },
    { city: "הראל", neighborhoods: DEFAULT_NB },
    { city: "הרדוף", neighborhoods: DEFAULT_NB },
    { city: "הררית", neighborhoods: DEFAULT_NB },
    { city: "הרצליה", neighborhoods: ["הרצליה פיתוח", "יד התשעה", "נווה ישראל", "נווה עמל", "נוה עובד", "שכונת הצוק"] },

    // ============== ז ==============
    { city: "זבדיאל", neighborhoods: DEFAULT_NB },
    { city: "זוהר", neighborhoods: DEFAULT_NB },
    { city: "זיקים", neighborhoods: DEFAULT_NB },
    { city: "זיתן", neighborhoods: DEFAULT_NB },
    { city: "זכרון יעקב", neighborhoods: DEFAULT_NB },
    { city: "זכריה", neighborhoods: DEFAULT_NB },
    { city: "זמר", neighborhoods: DEFAULT_NB },
    { city: "זמרת", neighborhoods: DEFAULT_NB },
    { city: "זנוח", neighborhoods: DEFAULT_NB },
    { city: "זרועה", neighborhoods: DEFAULT_NB },
    { city: "זרחיה", neighborhoods: DEFAULT_NB },

    // ============== ח ==============
    { city: "חבצלת השרון", neighborhoods: DEFAULT_NB },
    { city: "חבר", neighborhoods: DEFAULT_NB },
    { city: "חברון", neighborhoods: DEFAULT_NB },
    { city: "חגור", neighborhoods: DEFAULT_NB },
    { city: "חגי", neighborhoods: DEFAULT_NB },
    { city: "חגלה", neighborhoods: DEFAULT_NB },
    { city: "חד-נס", neighborhoods: DEFAULT_NB },
    { city: "חדיד", neighborhoods: DEFAULT_NB },
    { city: "חדרה", neighborhoods: ["מרכז", "אחוזה", "בית אליעזר", "ברנדייס", "גבעת אולגה", "נווה חיים", "נחליאל", "שכונת הגנים"] },
    { city: "חולדה", neighborhoods: DEFAULT_NB },
    { city: "חולון", neighborhoods: ["מרכז", "אגרובנק", "בת חן", "ג'סי כהן", "נווה פנחס", "קריית בן גוריון", "קריית אברהם", "קריית עבודה", "קריית שרת", "צהלה", "תל גיבורים"] },
    { city: "חולית", neighborhoods: DEFAULT_NB },
    { city: "חולתה", neighborhoods: DEFAULT_NB },
    { city: "חוסן", neighborhoods: DEFAULT_NB },
    { city: "חופית", neighborhoods: DEFAULT_NB },
    { city: "חוקוק", neighborhoods: DEFAULT_NB },
    { city: "חורשים", neighborhoods: DEFAULT_NB },
    { city: "חזון", neighborhoods: DEFAULT_NB },
    { city: "חיבת ציון", neighborhoods: DEFAULT_NB },
    { city: "חיפה", neighborhoods: ["רמת אשכול", "ורדיה", "רמת בגין", "רמת ספיר", "רמת אלון", "רמות רמז", "רמת גולדה", "רמת אלמוגי", "רובע כרמל", "כרמל צרפתי", "מערב חיפה", "רובע המפרץ", "קריית אליעזר", "קריית שמואל", "רובע רמות הכרמל", "אחוזת שמואל", "ארד אל-יהוד", "בת גלים", "גבעת אורנים", "דניה", "הדר הכרמל", "המושבה הגרמנית", "העיר התחתית", "ואדי ניסנאס", "ואדי סאליב", "חליסה", "כבאביר", "כפר סמיר", "כרמל מערבי", "מרכז הכרמל", "נאות פרס", "נווה דוד", "נווה שאנן", "נחלה", "קריית חיים", "קריית שפרינצק", "רוממה", "רמת הנשיא", "רמת ויז'ניץ", "תחנת הכרמל"] },
    { city: "חירות", neighborhoods: DEFAULT_NB },
    { city: "חלוץ", neighborhoods: DEFAULT_NB },
    { city: "חלץ", neighborhoods: DEFAULT_NB },
    { city: "חמד", neighborhoods: DEFAULT_NB },
    { city: "חמדיה", neighborhoods: DEFAULT_NB },
    { city: "חמדת", neighborhoods: DEFAULT_NB },
    { city: "חניאל", neighborhoods: DEFAULT_NB },
    { city: "חניתה", neighborhoods: DEFAULT_NB },
    { city: "חנתון", neighborhoods: DEFAULT_NB },
    { city: "חספין", neighborhoods: DEFAULT_NB },
    { city: "חפץ חיים", neighborhoods: DEFAULT_NB },
    { city: "חפצי-בה", neighborhoods: DEFAULT_NB },
    { city: "חצב", neighborhoods: DEFAULT_NB },
    { city: "חצבה", neighborhoods: DEFAULT_NB },
    { city: "חצור-אשדוד", neighborhoods: DEFAULT_NB },
    { city: "חצור הגלילית", neighborhoods: DEFAULT_NB },
    { city: "חצרים", neighborhoods: DEFAULT_NB },
    { city: "חרב לאת", neighborhoods: DEFAULT_NB },
    { city: "חרוצים", neighborhoods: DEFAULT_NB },
    { city: "חריש", neighborhoods: DEFAULT_NB },
    { city: "חרמש", neighborhoods: DEFAULT_NB },
    { city: "חרשים", neighborhoods: DEFAULT_NB },

    // ============== ט ==============
    { city: "טבריה", neighborhoods: ["מרכז", "חצר היהודים בטבריה", "קריית צאנז", "קריית שמואל", "שכונת שלושת הבתים", "שכונת הגבעה"] },
    { city: "טייבה", neighborhoods: ["מרכז", "שכונה א", "שכונה ב"] },
    { city: "טירת יהודה", neighborhoods: DEFAULT_NB },
    { city: "טירת כרמל", neighborhoods: DEFAULT_NB },
    { city: "טירת צבי", neighborhoods: DEFAULT_NB },
    { city: "טל-אל", neighborhoods: DEFAULT_NB },
    { city: "טל שחר", neighborhoods: DEFAULT_NB },
    { city: "טללים", neighborhoods: DEFAULT_NB },
    { city: "טמרה", neighborhoods: DEFAULT_NB },
    { city: "טמרה (יזרעאל)", neighborhoods: DEFAULT_NB },
    { city: "טפחות", neighborhoods: DEFAULT_NB },

    // ============== י ==============
    { city: "יבול", neighborhoods: DEFAULT_NB },
    { city: "יבנאל", neighborhoods: DEFAULT_NB },
    { city: "יבנה", neighborhoods: ["מרכז", "אזור התעשייה", "שכונת הנביאים"] },
    { city: "יגור", neighborhoods: DEFAULT_NB },
    { city: "יגל", neighborhoods: DEFAULT_NB },
    { city: "יד בנימין", neighborhoods: DEFAULT_NB },
    { city: "יד השמונה", neighborhoods: DEFAULT_NB },
    { city: "יד חנה", neighborhoods: DEFAULT_NB },
    { city: "יד מרדכי", neighborhoods: DEFAULT_NB },
    { city: "יד נתן", neighborhoods: DEFAULT_NB },
    { city: "יד רמב\"ם", neighborhoods: DEFAULT_NB },
    { city: "ידידה", neighborhoods: DEFAULT_NB },
    { city: "יהוד-מונוסון", neighborhoods: ["יהוד", "מונוסון", "שכונת הרימון"] },
    { city: "יהל", neighborhoods: DEFAULT_NB },
    { city: "יובל", neighborhoods: DEFAULT_NB },
    { city: "יובלים", neighborhoods: DEFAULT_NB },
    { city: "יודפת", neighborhoods: DEFAULT_NB },
    { city: "יונתן", neighborhoods: DEFAULT_NB },
    { city: "יושיביה", neighborhoods: DEFAULT_NB },
    { city: "יזרעאל", neighborhoods: DEFAULT_NB },
    { city: "יחיעם", neighborhoods: DEFAULT_NB },
    { city: "יטבתה", neighborhoods: DEFAULT_NB },
    { city: "יכיני", neighborhoods: DEFAULT_NB },
    { city: "ינוב", neighborhoods: DEFAULT_NB },
    { city: "ינון", neighborhoods: DEFAULT_NB },
    { city: "יסוד המעלה", neighborhoods: DEFAULT_NB },
    { city: "יסודות", neighborhoods: DEFAULT_NB },
    { city: "יסעור", neighborhoods: DEFAULT_NB },
    { city: "יעד", neighborhoods: DEFAULT_NB },
    { city: "יעל", neighborhoods: DEFAULT_NB },
    { city: "יעף", neighborhoods: DEFAULT_NB },
    { city: "יערה", neighborhoods: DEFAULT_NB },
    { city: "יפיע", neighborhoods: DEFAULT_NB },
    { city: "יפעת", neighborhoods: DEFAULT_NB },
    { city: "יפתח", neighborhoods: DEFAULT_NB },
    { city: "יציץ", neighborhoods: DEFAULT_NB },
    { city: "יקום", neighborhoods: DEFAULT_NB },
    { city: "יקנעם (מושבה)", neighborhoods: DEFAULT_NB },
    { city: "יקנעם עילית", neighborhoods: ["מרכז", "שכונת הגבעה"] },
    { city: "יראון", neighborhoods: DEFAULT_NB },
    { city: "ירדנה", neighborhoods: DEFAULT_NB },
    { city: "ירוחם", neighborhoods: DEFAULT_NB },
    { city: "ירחיב", neighborhoods: DEFAULT_NB },
    { city: "ירושלים", neighborhoods: ["קרית משה", "רחביה", "גבעת שאול", "רמות", "גילה", "קטמון", "בקעה", "מעלות דפנה", "הר נוף", "פסגת זאב", "מלחה", "עין כרם", "תלפיות", "ארנונה", "א-טור", "אבו תור", "אבן ישראל", "אהל משה", "אוהל שלמה", "אל-אמירה", "בית אורות", "בית דוד", "בית הכרם", "בית וגן", "בית יוסף", "בית יעקב", "בית ישראל", "בתי אונגרין", "בתי הורודנא", "בתי הורנשטיין", "בתי ויטנברג", "בתי ורשה", "בתי ורנר", "בתי מונקאטש", "בתי מינסק", "בתי נייטין", "בתי ניסן ב\"ק", "בתי ראנד", "גאולה", "גבעת אורנים", "גבעת המבתר", "גבעת המטוס", "גבעת השקד", "גבעת מרדכי", "גבעת משה", "גבעת משואה", "גבעת רם", "גבעת שאול ב'", "גוננים", "הגבעה הצרפתית", "הולילנד", "המושבה הגרמנית", "המושבה היוונית", "הר הצופים", "הר חומה", "הר חוצבים", "זיכרון טוביה", "זיכרון יוסף", "זיכרון משה", "חומת שמואל", "חצר שטרויס", "טלביה", "ימין משה", "יפה נוף", "כפר התימנים בשילוח", "כרם אברהם", "מוסררה", "מוצא", "מזכרת משה", "מחנה הפליטים שועפאט", "מחנה יהודה", "מחנה ישראל", "מחניים", "ממילא", "מעלה הזיתים", "מקור ברוך", "מקור חיים", "מרחביה", "משכנות ישראל", "משכנות שאננים", "נווה גרנות", "נווה יעקב", "נווה שאנן", "נוף ציון", "נחלת אחים", "נחלת צבי", "נחלת צדוק", "נחלת שבעה", "נחלת שמעון", "ניות", "סוכת שלום", "סילואן", "סנהדריה", "סנהדריה המורחבת", "עזרת ישראל", "עזרת תורה", "עיר גנים", "עץ חיים", "פת", "צור באהר", "צמרת הבירה", "קדמת ציון", "קריית אונסדורף", "קריית בעלז", "קריית היובל", "קריית הלאום", "קריית הממשלה", "קריית הממשלה (מזרח ירושלים)", "קריית וולפסון", "קריית מטרסדורף", "קריית מנחם", "קריית משה", "קריית צאנז", "קריית שומרי אמונים", "קריית שמואל", "ראס אל-עמוד", "רוממה", "רמות אלון", "רמות פולין", "רמת אשכול", "רמת בית הכרם", "רמת דניה", "רמת שלמה", "רמת שרת", "רסקו", "שיכון הרבנים", "שיכון חב\"ד", "שיכון פאג\"י", "שכונת אחווה", "שכונת אמת המים התחתונה", "שכונת הבוכרים", "שכונת הפועלים", "שכונת שמעון הצדיק", "שמואל הנביא", "שערי חסד", "שערי ירושלים", "שערי צדק", "תל ארזה", "תלפיות מזרח"] },
    { city: "ירקונה", neighborhoods: DEFAULT_NB },
    { city: "ישע", neighborhoods: DEFAULT_NB },
    { city: "ישעי", neighborhoods: DEFAULT_NB },
    { city: "ישרש", neighborhoods: DEFAULT_NB },
    { city: "יתד", neighborhoods: DEFAULT_NB },

    // ============== כ ==============
    { city: "כברי", neighborhoods: DEFAULT_NB },
    { city: "כדורי", neighborhoods: DEFAULT_NB },
    { city: "כדיתה", neighborhoods: DEFAULT_NB },
    { city: "כוכב מיכאל", neighborhoods: DEFAULT_NB },
    { city: "כורזים", neighborhoods: DEFAULT_NB },
    { city: "כחל", neighborhoods: DEFAULT_NB },
    { city: "כחלה", neighborhoods: DEFAULT_NB },
    { city: "כיסופים", neighborhoods: DEFAULT_NB },
    { city: "כישור", neighborhoods: DEFAULT_NB },
    { city: "כליל", neighborhoods: DEFAULT_NB },
    { city: "כלנית", neighborhoods: DEFAULT_NB },
    { city: "כמאנה", neighborhoods: DEFAULT_NB },
    { city: "כמהין", neighborhoods: DEFAULT_NB },
    { city: "כמון", neighborhoods: DEFAULT_NB },
    { city: "כנות", neighborhoods: DEFAULT_NB },
    { city: "כנף", neighborhoods: DEFAULT_NB },
    { city: "כנרת (מושבה)", neighborhoods: DEFAULT_NB },
    { city: "כנרת (קבוצה)", neighborhoods: DEFAULT_NB },
    { city: "כסיפה", neighborhoods: DEFAULT_NB },
    { city: "כסלון", neighborhoods: DEFAULT_NB },
    { city: "כפר אביב", neighborhoods: DEFAULT_NB },
    { city: "כפר אוריה", neighborhoods: DEFAULT_NB },
    { city: "כפר אחים", neighborhoods: DEFAULT_NB },
    { city: "כפר ביאליק", neighborhoods: DEFAULT_NB },
    { city: "כפר ביל\"ו", neighborhoods: DEFAULT_NB },
    { city: "כפר בלום", neighborhoods: DEFAULT_NB },
    { city: "כפר בן נון", neighborhoods: DEFAULT_NB },
    { city: "כפר ברא", neighborhoods: DEFAULT_NB },
    { city: "כפר ברוך", neighborhoods: DEFAULT_NB },
    { city: "כפר גדעון", neighborhoods: DEFAULT_NB },
    { city: "כפר גלים", neighborhoods: DEFAULT_NB },
    { city: "כפר גליקסון", neighborhoods: DEFAULT_NB },
    { city: "כפר גלעדי", neighborhoods: DEFAULT_NB },
    { city: "כפר דניאל", neighborhoods: DEFAULT_NB },
    { city: "כפר החורש", neighborhoods: DEFAULT_NB },
    { city: "כפר המכבי", neighborhoods: DEFAULT_NB },
    { city: "כפר הנגיד", neighborhoods: DEFAULT_NB },
    { city: "כפר הנוער הדתי", neighborhoods: DEFAULT_NB },
    { city: "כפר הנשיא", neighborhoods: DEFAULT_NB },
    { city: "כפר הס", neighborhoods: DEFAULT_NB },
    { city: "כפר הרא\"ה", neighborhoods: DEFAULT_NB },
    { city: "כפר הרי\"ף", neighborhoods: DEFAULT_NB },
    { city: "כפר ויתקין", neighborhoods: DEFAULT_NB },
    { city: "כפר ורבורג", neighborhoods: DEFAULT_NB },
    { city: "כפר ורדים", neighborhoods: DEFAULT_NB },
    { city: "כפר זוהרים", neighborhoods: DEFAULT_NB },
    { city: "כפר זיתים", neighborhoods: DEFAULT_NB },
    { city: "כפר חב\"ד", neighborhoods: DEFAULT_NB },
    { city: "כפר חושן", neighborhoods: DEFAULT_NB },
    { city: "כפר חיטים", neighborhoods: DEFAULT_NB },
    { city: "כפר חיים", neighborhoods: DEFAULT_NB },
    { city: "כפר חנניה", neighborhoods: DEFAULT_NB },
    { city: "כפר חסידים א'", neighborhoods: DEFAULT_NB },
    { city: "כפר חסידים ב'", neighborhoods: DEFAULT_NB },
    { city: "כפר חרוב", neighborhoods: DEFAULT_NB },
    { city: "כפר טרומן", neighborhoods: DEFAULT_NB },
    { city: "כפר ידידיה", neighborhoods: DEFAULT_NB },
    { city: "כפר יהושע", neighborhoods: DEFAULT_NB },
    { city: "כפר יונה", neighborhoods: DEFAULT_NB },
    { city: "כפר יחזקאל", neighborhoods: DEFAULT_NB },
    { city: "כפר יעבץ", neighborhoods: DEFAULT_NB },
    { city: "כפר מימון", neighborhoods: DEFAULT_NB },
    { city: "כפר מל\"ל", neighborhoods: DEFAULT_NB },
    { city: "כפר מנחם", neighborhoods: DEFAULT_NB },
    { city: "כפר מסריק", neighborhoods: DEFAULT_NB },
    { city: "כפר מצר", neighborhoods: DEFAULT_NB },
    { city: "כפר מרדכי", neighborhoods: DEFAULT_NB },
    { city: "כפר נטר", neighborhoods: DEFAULT_NB },
    { city: "כפר סאלד", neighborhoods: DEFAULT_NB },
    { city: "כפר סבא", neighborhoods: ["מרכז", "רמת כפר סבא", "נווה ים", "גני תקווה", "שכונת יוספטל"] },
    { city: "כפר סילבר", neighborhoods: DEFAULT_NB },
    { city: "כפר סירקין", neighborhoods: DEFAULT_NB },
    { city: "כפר עבודה", neighborhoods: DEFAULT_NB },
    { city: "כפר עזה", neighborhoods: DEFAULT_NB },
    { city: "כפר פינס", neighborhoods: DEFAULT_NB },
    { city: "כפר קיש", neighborhoods: DEFAULT_NB },
    { city: "כפר ראש הנקרה", neighborhoods: DEFAULT_NB },
    { city: "כפר רוזנואלד (זרעית)", neighborhoods: DEFAULT_NB },
    { city: "כפר רופין", neighborhoods: DEFAULT_NB },
    { city: "כפר רות", neighborhoods: DEFAULT_NB },
    { city: "כפר שמאי", neighborhoods: DEFAULT_NB },
    { city: "כפר שמואל", neighborhoods: DEFAULT_NB },
    { city: "כפר שמריהו", neighborhoods: DEFAULT_NB },
    { city: "כפר תבור", neighborhoods: DEFAULT_NB },
    { city: "כרי דשא", neighborhoods: DEFAULT_NB },
    { city: "כרכום", neighborhoods: DEFAULT_NB },
    { city: "כרם ביבנה (ישיבה)", neighborhoods: DEFAULT_NB },
    { city: "כרם בן זמרה", neighborhoods: DEFAULT_NB },
    { city: "כרם בן שמן", neighborhoods: DEFAULT_NB },
    { city: "כרם מהר\"ל", neighborhoods: DEFAULT_NB },
    { city: "כרם שלום", neighborhoods: DEFAULT_NB },
    { city: "כרמי יוסף", neighborhoods: DEFAULT_NB },
    { city: "כרמי קטיף", neighborhoods: DEFAULT_NB },
    { city: "כרמיאל", neighborhoods: DEFAULT_NB },
    { city: "כרמיה", neighborhoods: DEFAULT_NB },
    { city: "כרמים", neighborhoods: DEFAULT_NB },

    // ============== ל ==============
    { city: "לביא", neighborhoods: DEFAULT_NB },
    { city: "לבנים", neighborhoods: DEFAULT_NB },
    { city: "להב", neighborhoods: DEFAULT_NB },
    { city: "להבות הבשן", neighborhoods: DEFAULT_NB },
    { city: "להבות חביבה", neighborhoods: DEFAULT_NB },
    { city: "להבים", neighborhoods: DEFAULT_NB },
    { city: "לוד", neighborhoods: ["מרכז", "כרמים", "נווה ישראל", "שכונת גאולים", "גני אביב", "גני איילון", "שכונת הרכבת"] },
    { city: "לוזית", neighborhoods: DEFAULT_NB },
    { city: "לוחמי הגיטאות", neighborhoods: DEFAULT_NB },
    { city: "לוטם", neighborhoods: DEFAULT_NB },
    { city: "לוטן", neighborhoods: DEFAULT_NB },
    { city: "לימן", neighborhoods: DEFAULT_NB },
    { city: "לכיש", neighborhoods: DEFAULT_NB },
    { city: "לפיד", neighborhoods: DEFAULT_NB },
    { city: "לפידות", neighborhoods: DEFAULT_NB },

    // ============== מ ==============
    { city: "מאור", neighborhoods: DEFAULT_NB },
    { city: "מאיר שפיה", neighborhoods: DEFAULT_NB },
    { city: "מבוא ביתר", neighborhoods: DEFAULT_NB },
    { city: "מבוא חמה", neighborhoods: DEFAULT_NB },
    { city: "מבוא מודיעים", neighborhoods: DEFAULT_NB },
    { city: "מבואות ים", neighborhoods: DEFAULT_NB },
    { city: "מבועים", neighborhoods: DEFAULT_NB },
    { city: "מבטחים", neighborhoods: DEFAULT_NB },
    { city: "מבקיעים", neighborhoods: DEFAULT_NB },
    { city: "מבשרת ציון", neighborhoods: DEFAULT_NB },
    { city: "מגדים", neighborhoods: DEFAULT_NB },
    { city: "מגדל", neighborhoods: DEFAULT_NB },
    { city: "מגדל העמק", neighborhoods: ["מרכז", "שכונת הגנים", "שכונה ב"] },
    { city: "מגידו", neighborhoods: DEFAULT_NB },
    { city: "מגל", neighborhoods: DEFAULT_NB },
    { city: "מגן", neighborhoods: DEFAULT_NB },
    { city: "מגן שאול", neighborhoods: DEFAULT_NB },
    { city: "מגשימים", neighborhoods: DEFAULT_NB },
    { city: "מדרך עוז", neighborhoods: DEFAULT_NB },
    { city: "מדרשת בן גוריון", neighborhoods: DEFAULT_NB },
    { city: "מדרשת רופין", neighborhoods: DEFAULT_NB },
    { city: "מודיעין-מכבים-רעות", neighborhoods: ["מע\"ר", "הכרמים", "הציפורים", "מוריה", "המגינים", "השבטים", "הנביאים", "משואה", "אבני חן", "שומרי החומות", "הנחלים", "בוכמן", "קייזר", "שמשוני"] },
    { city: "מודיעין עילית", neighborhoods: ["קרית ספר", "ברכפלד", "נאות הפסגה", "גרין פארק", "חפציבה"] },
    { city: "מולדת", neighborhoods: DEFAULT_NB },
    { city: "מוצא עילית", neighborhoods: DEFAULT_NB },
    { city: "מורן", neighborhoods: DEFAULT_NB },
    { city: "מורשת", neighborhoods: DEFAULT_NB },
    { city: "מזור", neighborhoods: DEFAULT_NB },
    { city: "מזכרת בתיה", neighborhoods: DEFAULT_NB },
    { city: "מזרע", neighborhoods: DEFAULT_NB },
    { city: "מזרעה", neighborhoods: DEFAULT_NB },
    { city: "מחולה", neighborhoods: DEFAULT_NB },
    { city: "מחניים", neighborhoods: DEFAULT_NB },
    { city: "מחסיה", neighborhoods: DEFAULT_NB },
    { city: "מטולה", neighborhoods: DEFAULT_NB },
    { city: "מטע", neighborhoods: DEFAULT_NB },
    { city: "מי עמי", neighborhoods: DEFAULT_NB },
    { city: "מיטב", neighborhoods: DEFAULT_NB },
    { city: "מיטל", neighborhoods: DEFAULT_NB },
    { city: "מייסר", neighborhoods: DEFAULT_NB },
    { city: "מיצר", neighborhoods: DEFAULT_NB },
    { city: "מירב", neighborhoods: DEFAULT_NB },
    { city: "מירון", neighborhoods: DEFAULT_NB },
    { city: "מישר", neighborhoods: DEFAULT_NB },
    { city: "מיתר", neighborhoods: DEFAULT_NB },
    { city: "מכחול", neighborhoods: DEFAULT_NB },
    { city: "מכמורת", neighborhoods: DEFAULT_NB },
    { city: "מכמנים", neighborhoods: DEFAULT_NB },
    { city: "מלאה", neighborhoods: DEFAULT_NB },
    { city: "מלילות", neighborhoods: DEFAULT_NB },
    { city: "מלכיה", neighborhoods: DEFAULT_NB },
    { city: "מנוחה", neighborhoods: DEFAULT_NB },
    { city: "מנוף", neighborhoods: DEFAULT_NB },
    { city: "מנות", neighborhoods: DEFAULT_NB },
    { city: "מנחמיה", neighborhoods: DEFAULT_NB },
    { city: "מנרה", neighborhoods: DEFAULT_NB },
    { city: "מנשית זבדה", neighborhoods: DEFAULT_NB },
    { city: "מסד", neighborhoods: DEFAULT_NB },
    { city: "מסדה", neighborhoods: DEFAULT_NB },
    { city: "מסילות", neighborhoods: DEFAULT_NB },
    { city: "מסילת ציון", neighborhoods: DEFAULT_NB },
    { city: "מסלול", neighborhoods: DEFAULT_NB },
    { city: "מעברות", neighborhoods: DEFAULT_NB },
    { city: "מעגלים", neighborhoods: DEFAULT_NB },
    { city: "מעגן", neighborhoods: DEFAULT_NB },
    { city: "מעגן מיכאל", neighborhoods: DEFAULT_NB },
    { city: "מעוז חיים", neighborhoods: DEFAULT_NB },
    { city: "מעונה", neighborhoods: DEFAULT_NB },
    { city: "מעין ברוך", neighborhoods: DEFAULT_NB },
    { city: "מעין צבי", neighborhoods: DEFAULT_NB },
    { city: "מעלה גלבוע", neighborhoods: DEFAULT_NB },
    { city: "מעלה גמלא", neighborhoods: DEFAULT_NB },
    { city: "מעלה החמישה", neighborhoods: DEFAULT_NB },
    { city: "מעלה עירון", neighborhoods: DEFAULT_NB },
    { city: "מעלה עמוס", neighborhoods: DEFAULT_NB },
    { city: "מעלות-תרשיחא", neighborhoods: DEFAULT_NB },
    { city: "מענית", neighborhoods: DEFAULT_NB },
    { city: "מעש", neighborhoods: DEFAULT_NB },
    { city: "מפלסים", neighborhoods: DEFAULT_NB },
    { city: "מצדות יהודה", neighborhoods: DEFAULT_NB },
    { city: "מצובה", neighborhoods: DEFAULT_NB },
    { city: "מצליח", neighborhoods: DEFAULT_NB },
    { city: "מצפה", neighborhoods: DEFAULT_NB },
    { city: "מצפה אבי\"ב", neighborhoods: DEFAULT_NB },
    { city: "מצפה אילן", neighborhoods: DEFAULT_NB },
    { city: "מצפה נטופה", neighborhoods: DEFAULT_NB },
    { city: "מצפה רמון", neighborhoods: DEFAULT_NB },
    { city: "מצר", neighborhoods: DEFAULT_NB },
    { city: "מקווה ישראל", neighborhoods: DEFAULT_NB },
    { city: "מרגליות", neighborhoods: DEFAULT_NB },
    { city: "מרום גולן", neighborhoods: DEFAULT_NB },
    { city: "מרחב עם", neighborhoods: DEFAULT_NB },
    { city: "מרחביה (מושב)", neighborhoods: DEFAULT_NB },
    { city: "מרחביה (קיבוץ)", neighborhoods: DEFAULT_NB },
    { city: "מרכז שפירא", neighborhoods: DEFAULT_NB },
    { city: "משאבי שדה", neighborhoods: DEFAULT_NB },
    { city: "משגב דב", neighborhoods: DEFAULT_NB },
    { city: "משגב עם", neighborhoods: DEFAULT_NB },
    { city: "משהד", neighborhoods: DEFAULT_NB },
    { city: "משואות יצחק", neighborhoods: DEFAULT_NB },
    { city: "משמר איילון", neighborhoods: DEFAULT_NB },
    { city: "משמר דוד", neighborhoods: DEFAULT_NB },
    { city: "משמר הירדן", neighborhoods: DEFAULT_NB },
    { city: "משמר הנגב", neighborhoods: DEFAULT_NB },
    { city: "משמר העמק", neighborhoods: DEFAULT_NB },
    { city: "משמר השבעה", neighborhoods: DEFAULT_NB },
    { city: "משמר השרון", neighborhoods: DEFAULT_NB },
    { city: "משמר יהודה", neighborhoods: DEFAULT_NB },
    { city: "משמרות", neighborhoods: DEFAULT_NB },
    { city: "משמרת", neighborhoods: DEFAULT_NB },
    { city: "משען", neighborhoods: DEFAULT_NB },
    { city: "מתן", neighborhoods: DEFAULT_NB },
    { city: "מתת", neighborhoods: DEFAULT_NB },

    // ============== נ ==============
    { city: "נאות גולן", neighborhoods: DEFAULT_NB },
    { city: "נאות הכיכר", neighborhoods: DEFAULT_NB },
    { city: "נאות מרדכי", neighborhoods: DEFAULT_NB },
    { city: "נאות סמדר", neighborhoods: DEFAULT_NB },
    { city: "נבטים", neighborhoods: DEFAULT_NB },
    { city: "נגבה", neighborhoods: DEFAULT_NB },
    { city: "נהורה", neighborhoods: DEFAULT_NB },
    { city: "נהלל", neighborhoods: DEFAULT_NB },
    { city: "נהריה", neighborhoods: ["מרכז", "גבעת זיו", "שכונת ים"] },
    { city: "נוב", neighborhoods: DEFAULT_NB },
    { city: "נוגה", neighborhoods: DEFAULT_NB },
    { city: "נוף הגליל", neighborhoods: ["הר יונה ג'", "רמות גולדה מאיר"] },
    { city: "נווה", neighborhoods: DEFAULT_NB },
    { city: "נווה אבות", neighborhoods: DEFAULT_NB },
    { city: "נווה אור", neighborhoods: DEFAULT_NB },
    { city: "נווה אטי\"ב", neighborhoods: DEFAULT_NB },
    { city: "נווה אילן", neighborhoods: DEFAULT_NB },
    { city: "נווה איתן", neighborhoods: DEFAULT_NB },
    { city: "נווה זוהר", neighborhoods: DEFAULT_NB },
    { city: "נווה זיו", neighborhoods: DEFAULT_NB },
    { city: "נווה חריף", neighborhoods: DEFAULT_NB },
    { city: "נווה ים", neighborhoods: DEFAULT_NB },
    { city: "נווה ימין", neighborhoods: DEFAULT_NB },
    { city: "נווה ירק", neighborhoods: DEFAULT_NB },
    { city: "נווה מבטח", neighborhoods: DEFAULT_NB },
    { city: "נווה מיכאל", neighborhoods: DEFAULT_NB },
    { city: "נווה שלום", neighborhoods: DEFAULT_NB },
    { city: "נועם", neighborhoods: DEFAULT_NB },
    { city: "נוף איילון", neighborhoods: DEFAULT_NB },
    { city: "נופית", neighborhoods: DEFAULT_NB },
    { city: "נופך", neighborhoods: DEFAULT_NB },
    { city: "נורדיה", neighborhoods: DEFAULT_NB },
    { city: "נורית", neighborhoods: DEFAULT_NB },
    { city: "נחושה", neighborhoods: DEFAULT_NB },
    { city: "נחל עוז", neighborhoods: DEFAULT_NB },
    { city: "נחלה", neighborhoods: DEFAULT_NB },
    { city: "נחלים", neighborhoods: DEFAULT_NB },
    { city: "נחם", neighborhoods: DEFAULT_NB },
    { city: "נחף", neighborhoods: DEFAULT_NB },
    { city: "נחשולים", neighborhoods: DEFAULT_NB },
    { city: "נחשון", neighborhoods: DEFAULT_NB },
    { city: "נחשונים", neighborhoods: DEFAULT_NB },
    { city: "נטועה", neighborhoods: DEFAULT_NB },
    { city: "נטור", neighborhoods: DEFAULT_NB },
    { city: "נטע", neighborhoods: DEFAULT_NB },
    { city: "נטעים", neighborhoods: DEFAULT_NB },
    { city: "נטף", neighborhoods: DEFAULT_NB },
    { city: "ניצן", neighborhoods: DEFAULT_NB },
    { city: "ניצן ב'", neighborhoods: DEFAULT_NB },
    { city: "ניצנה (קהילת חינוך)", neighborhoods: DEFAULT_NB },
    { city: "ניצני סיני", neighborhoods: DEFAULT_NB },
    { city: "ניצני עוז", neighborhoods: DEFAULT_NB },
    { city: "ניצנים", neighborhoods: DEFAULT_NB },
    { city: "ניר אליהו", neighborhoods: DEFAULT_NB },
    { city: "ניר בנים", neighborhoods: DEFAULT_NB },
    { city: "ניר גלים", neighborhoods: DEFAULT_NB },
    { city: "ניר דוד (תל עמל)", neighborhoods: DEFAULT_NB },
    { city: "ניר ח\"ן", neighborhoods: DEFAULT_NB },
    { city: "ניר יפה", neighborhoods: DEFAULT_NB },
    { city: "ניר יצחק", neighborhoods: DEFAULT_NB },
    { city: "ניר ישראל", neighborhoods: DEFAULT_NB },
    { city: "ניר משה", neighborhoods: DEFAULT_NB },
    { city: "ניר עוז", neighborhoods: DEFAULT_NB },
    { city: "ניר עם", neighborhoods: DEFAULT_NB },
    { city: "ניר עציון", neighborhoods: DEFAULT_NB },
    { city: "ניר עקיבא", neighborhoods: DEFAULT_NB },
    { city: "ניר צבי", neighborhoods: DEFAULT_NB },
    { city: "נירים", neighborhoods: DEFAULT_NB },
    { city: "נירית", neighborhoods: DEFAULT_NB },
    { city: "נמרוד", neighborhoods: DEFAULT_NB },
    { city: "נס הרים", neighborhoods: DEFAULT_NB },
    { city: "נס עמים", neighborhoods: DEFAULT_NB },
    { city: "נס ציונה", neighborhoods: ["מרכז", "קרית האולימפיאדה", "שכונת הגנים", "מרכז מסחרי", "גבעת מיכאל", "טירת שלום", "כפר אהרון"] },
    { city: "נעורים", neighborhoods: DEFAULT_NB },
    { city: "נען", neighborhoods: DEFAULT_NB },
    { city: "נצר חזני", neighborhoods: DEFAULT_NB },
    { city: "נצר סרני", neighborhoods: DEFAULT_NB },
    { city: "נצרת", neighborhoods: ["מרכז", "עיר עתיקה", "רם"] },
    { city: "נשר", neighborhoods: ["בן דור", "גבעת נשר", "רמות יצחק", "תל חנן"] },
    { city: "נתיב הל\"ה", neighborhoods: DEFAULT_NB },
    { city: "נתיב העשרה", neighborhoods: DEFAULT_NB },
    { city: "נתיב השיירה", neighborhoods: DEFAULT_NB },
    { city: "נתיבות", neighborhoods: ["מרכז", "שכונה ב", "גינות"] },
    { city: "נתניה", neighborhoods: ["קרית השרון", "רמת פולג", "נווה גנים", "עיר ימים", "צוקי ים", "מרכז", "נאות הרצל", "קריית נורדאו", "קריית ספיר"] },

    // ============== ס ==============
    { city: "סאסא", neighborhoods: DEFAULT_NB },
    { city: "סביון", neighborhoods: DEFAULT_NB },
    { city: "סגולה", neighborhoods: DEFAULT_NB },
    { city: "סולם", neighborhoods: DEFAULT_NB },
    { city: "סופה", neighborhoods: DEFAULT_NB },
    { city: "סלמה", neighborhoods: DEFAULT_NB },
    { city: "סעד", neighborhoods: DEFAULT_NB },
    { city: "סער", neighborhoods: DEFAULT_NB },
    { city: "ספיר", neighborhoods: DEFAULT_NB },
    { city: "סתריה", neighborhoods: DEFAULT_NB },

    // ============== ע ==============
    { city: "עברון", neighborhoods: DEFAULT_NB },
    { city: "עגור", neighborhoods: DEFAULT_NB },
    { city: "עדי", neighborhoods: DEFAULT_NB },
    { city: "עדנים", neighborhoods: DEFAULT_NB },
    { city: "עוזה", neighborhoods: DEFAULT_NB },
    { city: "עולש", neighborhoods: DEFAULT_NB },
    { city: "עומר", neighborhoods: DEFAULT_NB },
    { city: "עופר", neighborhoods: DEFAULT_NB },
    { city: "עופרה", neighborhoods: DEFAULT_NB },
    { city: "עוצם", neighborhoods: DEFAULT_NB },
    { city: "עזר", neighborhoods: DEFAULT_NB },
    { city: "עזריאל", neighborhoods: DEFAULT_NB },
    { city: "עזריה", neighborhoods: DEFAULT_NB },
    { city: "עזריקם", neighborhoods: DEFAULT_NB },
    { city: "עידן", neighborhoods: DEFAULT_NB },
    { city: "עיינות", neighborhoods: DEFAULT_NB },
    { city: "עילוט", neighborhoods: DEFAULT_NB },
    { city: "עין איילה", neighborhoods: DEFAULT_NB },
    { city: "עין גב", neighborhoods: DEFAULT_NB },
    { city: "עין גדי", neighborhoods: DEFAULT_NB },
    { city: "עין דור", neighborhoods: DEFAULT_NB },
    { city: "עין הבשור", neighborhoods: DEFAULT_NB },
    { city: "עין הוד", neighborhoods: DEFAULT_NB },
    { city: "עין החורש", neighborhoods: DEFAULT_NB },
    { city: "עין המפרץ", neighborhoods: DEFAULT_NB },
    { city: "עין הנצי\"ב", neighborhoods: DEFAULT_NB },
    { city: "עין העמק", neighborhoods: DEFAULT_NB },
    { city: "עין השופט", neighborhoods: DEFAULT_NB },
    { city: "עין השלושה", neighborhoods: DEFAULT_NB },
    { city: "עין ורד", neighborhoods: DEFAULT_NB },
    { city: "עין זיוון", neighborhoods: DEFAULT_NB },
    { city: "עין חוד", neighborhoods: DEFAULT_NB },
    { city: "עין חצבה", neighborhoods: DEFAULT_NB },
    { city: "עין חרוד (איחוד)", neighborhoods: DEFAULT_NB },
    { city: "עין חרוד (מאוחד)", neighborhoods: DEFAULT_NB },
    { city: "עין יהב", neighborhoods: DEFAULT_NB },
    { city: "עין יעקב", neighborhoods: DEFAULT_NB },
    { city: "עין כרם-בי\"ס חקלאי", neighborhoods: DEFAULT_NB },
    { city: "עין כרמל", neighborhoods: DEFAULT_NB },
    { city: "עין עירון", neighborhoods: DEFAULT_NB },
    { city: "עין צורים", neighborhoods: DEFAULT_NB },
    { city: "עין שמר", neighborhoods: DEFAULT_NB },
    { city: "עין שריד", neighborhoods: DEFAULT_NB },
    { city: "עין תמר", neighborhoods: DEFAULT_NB },
    { city: "עינת", neighborhoods: DEFAULT_NB },
    { city: "עיר אובות", neighborhoods: DEFAULT_NB },
    { city: "עכו", neighborhoods: ["עיר עתיקה", "וולפסון", "נווה אורים", "בן עמי"] },
    { city: "עלומים", neighborhoods: DEFAULT_NB },
    { city: "עלמה", neighborhoods: DEFAULT_NB },
    { city: "עמוקה", neighborhoods: DEFAULT_NB },
    { city: "עמיחי", neighborhoods: DEFAULT_NB },
    { city: "עמינדב", neighborhoods: DEFAULT_NB },
    { city: "עמיעד", neighborhoods: DEFAULT_NB },
    { city: "עמיעוז", neighborhoods: DEFAULT_NB },
    { city: "עמיקם", neighborhoods: DEFAULT_NB },
    { city: "עמיר", neighborhoods: DEFAULT_NB },
    { city: "עמקה", neighborhoods: DEFAULT_NB },
    { city: "עפולה", neighborhoods: ["מרכז", "שכונת ד", "שכונת המשכנות", "קריית צאנז", "גבעת המורה", "עפולה עילית"] },
    { city: "עצמון שגב", neighborhoods: DEFAULT_NB },
    { city: "ערד", neighborhoods: DEFAULT_NB },
    { city: "ערוגות", neighborhoods: DEFAULT_NB },
    { city: "עשרת", neighborhoods: DEFAULT_NB },
    { city: "עתלית", neighborhoods: DEFAULT_NB },

    // ============== פ ==============
    { city: "פארן", neighborhoods: DEFAULT_NB },
    { city: "פדויים", neighborhoods: DEFAULT_NB },
    { city: "פדיה", neighborhoods: DEFAULT_NB },
    { city: "פוריה - כפר עבודה", neighborhoods: DEFAULT_NB },
    { city: "פוריה - נווה עובד", neighborhoods: DEFAULT_NB },
    { city: "פוריה עילית", neighborhoods: DEFAULT_NB },
    { city: "פורת", neighborhoods: DEFAULT_NB },
    { city: "פטיש", neighborhoods: DEFAULT_NB },
    { city: "פלך", neighborhoods: DEFAULT_NB },
    { city: "פלמחים", neighborhoods: DEFAULT_NB },
    { city: "פני חבר", neighborhoods: DEFAULT_NB },
    { city: "פעמי תש\"ז", neighborhoods: DEFAULT_NB },
    { city: "פקיעין (בוקייעה)", neighborhoods: DEFAULT_NB },
    { city: "פקיעין חדשה", neighborhoods: DEFAULT_NB },
    { city: "פרדס חנה-כרכור", neighborhoods: DEFAULT_NB },
    { city: "פרדסיה", neighborhoods: DEFAULT_NB },
    { city: "פרוד", neighborhoods: DEFAULT_NB },
    { city: "פרזון", neighborhoods: DEFAULT_NB },
    { city: "פרי גן", neighborhoods: DEFAULT_NB },
    { city: "פתחיה", neighborhoods: DEFAULT_NB },
    { city: "פתח תקווה", neighborhoods: ["קרית אריה", "נווה עוז", "שיכון דן", "מרכז", "כפר גנים", "סגולה", "רובע יזרעאל", "אם המושבות", "אם המושבות החדשה", "הדר גנים-עמישב", "כפר אברהם", "מחנה יהודה", "נווה גן", "עין גנים", "קריית מטלון"] },

    // ============== צ ==============
    { city: "צאלים", neighborhoods: DEFAULT_NB },
    { city: "צביה", neighborhoods: DEFAULT_NB },
    { city: "צבעון", neighborhoods: DEFAULT_NB },
    { city: "צובה", neighborhoods: DEFAULT_NB },
    { city: "צוחר", neighborhoods: DEFAULT_NB },
    { city: "צופיה", neighborhoods: DEFAULT_NB },
    { city: "צופית", neighborhoods: DEFAULT_NB },
    { city: "צופר", neighborhoods: DEFAULT_NB },
    { city: "צוקי ים", neighborhoods: DEFAULT_NB },
    { city: "צוקים", neighborhoods: DEFAULT_NB },
    { city: "צור הדסה", neighborhoods: DEFAULT_NB },
    { city: "צור יצחק", neighborhoods: DEFAULT_NB },
    { city: "צור משה", neighborhoods: DEFAULT_NB },
    { city: "צור נתן", neighborhoods: DEFAULT_NB },
    { city: "צוריאל", neighborhoods: DEFAULT_NB },
    { city: "צורית", neighborhoods: DEFAULT_NB },
    { city: "ציפורי", neighborhoods: DEFAULT_NB },
    { city: "צלפון", neighborhoods: DEFAULT_NB },
    { city: "צנדלה", neighborhoods: DEFAULT_NB },
    { city: "צפריה", neighborhoods: DEFAULT_NB },
    { city: "צפרירים", neighborhoods: DEFAULT_NB },
    { city: "צפת", neighborhoods: ["מרכז", "עיר עתיקה", "כנען", "שכונת ה", "רמת ורבר", "צפת העתיקה"] },
    { city: "צרופה", neighborhoods: DEFAULT_NB },
    { city: "צרעה", neighborhoods: DEFAULT_NB },

    // ============== ק ==============
    { city: "קבוצת יבנה", neighborhoods: DEFAULT_NB },
    { city: "קדימה-צורן", neighborhoods: DEFAULT_NB },
    { city: "קדמה", neighborhoods: DEFAULT_NB },
    { city: "קדמת צבי", neighborhoods: DEFAULT_NB },
    { city: "קדרון", neighborhoods: DEFAULT_NB },
    { city: "קדרים", neighborhoods: DEFAULT_NB },
    { city: "קוממיות", neighborhoods: DEFAULT_NB },
    { city: "קורנית", neighborhoods: DEFAULT_NB },
    { city: "קטורה", neighborhoods: DEFAULT_NB },
    { city: "קיסריה", neighborhoods: DEFAULT_NB },
    { city: "קלחים", neighborhoods: DEFAULT_NB },
    { city: "קלע", neighborhoods: DEFAULT_NB },
    { city: "קציר", neighborhoods: DEFAULT_NB },
    { city: "קצרין", neighborhoods: DEFAULT_NB },
    { city: "קרית אונו", neighborhoods: ["מרכז", "גבעת שמואל", "נאות אפק"] },
    { city: "קרית אתא", neighborhoods: ["מרכז", "שכונת יוספטל", "שכונת הכרמל"] },
    { city: "קרית ביאליק", neighborhoods: ["מרכז", "שכונה א", "קרית חיים מזרחית", "עכברה", "גבעת הרקפות", "נאות אפק"] },
    { city: "קרית גת", neighborhoods: ["מרכז", "שכונה ב", "כנות"] },
    { city: "קרית טבעון", neighborhoods: DEFAULT_NB },
    { city: "קרית ים", neighborhoods: DEFAULT_NB },
    { city: "קרית יערים", neighborhoods: DEFAULT_NB },
    { city: "קרית מוצקין", neighborhoods: ["מרכז", "שכונת גורדון", "קרית חיים"] },
    { city: "קרית מלאכי", neighborhoods: DEFAULT_NB },
    { city: "קרית ענבים", neighborhoods: DEFAULT_NB },
    { city: "קרית עקרון", neighborhoods: DEFAULT_NB },
    { city: "קרית שלמה", neighborhoods: DEFAULT_NB },
    { city: "קרית שמונה", neighborhoods: ["מרכז", "שכונת תל חי", "צפון"] },
    { city: "קשת", neighborhoods: DEFAULT_NB },

    // ============== ר ==============
    { city: "ראש העין", neighborhoods: ["מרכז", "נוות אפק", "כפר אברהם"] },
    { city: "ראש פינה", neighborhoods: DEFAULT_NB },
    { city: "ראשון לציון", neighborhoods: ["נווה דקלים", "רמת אליהו", "שיכון ותיקים", "מרכז", "נחלת יהודה", "עולי ציון", "צור שלום"] },
    { city: "רבדים", neighborhoods: DEFAULT_NB },
    { city: "רביבים", neighborhoods: DEFAULT_NB },
    { city: "רביד", neighborhoods: DEFAULT_NB },
    { city: "רגבה", neighborhoods: DEFAULT_NB },
    { city: "רגבים", neighborhoods: DEFAULT_NB },
    { city: "רהט", neighborhoods: ["מרכז", "שכונה ב", "שכונה ג"] },
    { city: "רווחה", neighborhoods: DEFAULT_NB },
    { city: "רוויה", neighborhoods: DEFAULT_NB },
    { city: "רוח מדבר", neighborhoods: DEFAULT_NB },
    { city: "רוחמה", neighborhoods: DEFAULT_NB },
    { city: "רחוב", neighborhoods: DEFAULT_NB },
    { city: "רחובות", neighborhoods: ["מרכז", "רמת רחובות", "נווה חוף", "שכונת הדרים", "כפר גנים", "שכונת רמז", "אושיות", "כפר גבירול", "כפר מרמורק", "פארק ת.מ.ר", "פסגת קרעטשניף", "קריית קרעטשניף", "קריית ויזניץ", "קריית ההגנה", "שכונת אפרים", "שכונת חבצלת"] },
    { city: "רינתיה", neighborhoods: DEFAULT_NB },
    { city: "רכסים", neighborhoods: DEFAULT_NB },
    { city: "רם-און", neighborhoods: DEFAULT_NB },
    { city: "רמות", neighborhoods: DEFAULT_NB },
    { city: "רמות השבים", neighborhoods: DEFAULT_NB },
    { city: "רמות מאיר", neighborhoods: DEFAULT_NB },
    { city: "רמות מנשה", neighborhoods: DEFAULT_NB },
    { city: "רמות נפתלי", neighborhoods: DEFAULT_NB },
    { city: "רמלה", neighborhoods: ["מרכז", "גן החיות", "שכונת עמישב"] },
    { city: "רמת גן", neighborhoods: ["מרכז", "בורוכוב", "נווה עוז", "כפר גנים", "נווה אפרים", "שעריים", "כפר אז\"ר", "מרום נווה", "קריית בורוכוב", "קריית קריניצי", "רמת אפעל", "רמת עמידר", "שכונת תל גנים", "תל בנימין", "תל השומר"] },
    { city: "רמת דוד", neighborhoods: DEFAULT_NB },
    { city: "רמת הכובש", neighborhoods: DEFAULT_NB },
    { city: "רמת השופט", neighborhoods: DEFAULT_NB },
    { city: "רמת השרון", neighborhoods: ["מרכז", "צהלה", "שכונת הצוק", "נווה מגן"] },
    { city: "רמת טראמפ", neighborhoods: DEFAULT_NB },
    { city: "רמת יוחנן", neighborhoods: DEFAULT_NB },
    { city: "רמת ישי", neighborhoods: DEFAULT_NB },
    { city: "רמת מגשימים", neighborhoods: DEFAULT_NB },
    { city: "רמת צבי", neighborhoods: DEFAULT_NB },
    { city: "רמת רזיאל", neighborhoods: DEFAULT_NB },
    { city: "רמת רחל", neighborhoods: DEFAULT_NB },
    { city: "רנן", neighborhoods: DEFAULT_NB },
    { city: "רעים", neighborhoods: DEFAULT_NB },
    { city: "רעננה", neighborhoods: ["מרכז", "נווה זמר", "גני עם", "שכונת ד"] },
    { city: "רקפת", neighborhoods: DEFAULT_NB },
    { city: "רשפון", neighborhoods: DEFAULT_NB },
    { city: "רשפים", neighborhoods: DEFAULT_NB },
    { city: "רתמים", neighborhoods: DEFAULT_NB },

    // ============== ש ==============
    { city: "שאר ישוב", neighborhoods: DEFAULT_NB },
    { city: "שבי דרום", neighborhoods: DEFAULT_NB },
    { city: "שבי ציון", neighborhoods: DEFAULT_NB },
    { city: "שגב-שלום", neighborhoods: DEFAULT_NB },
    { city: "שדה אילן", neighborhoods: DEFAULT_NB },
    { city: "שדה אליהו", neighborhoods: DEFAULT_NB },
    { city: "שדה אליעזר", neighborhoods: DEFAULT_NB },
    { city: "שדה בוקר", neighborhoods: DEFAULT_NB },
    { city: "שדה דוד", neighborhoods: DEFAULT_NB },
    { city: "שדה ורבורג", neighborhoods: DEFAULT_NB },
    { city: "שדה יואב", neighborhoods: DEFAULT_NB },
    { city: "שדה יעקב", neighborhoods: DEFAULT_NB },
    { city: "שדה יצחק", neighborhoods: DEFAULT_NB },
    { city: "שדה משה", neighborhoods: DEFAULT_NB },
    { city: "שדה נחום", neighborhoods: DEFAULT_NB },
    { city: "שדה נחמיה", neighborhoods: DEFAULT_NB },
    { city: "שדה ניצן", neighborhoods: DEFAULT_NB },
    { city: "שדה עוזיהו", neighborhoods: DEFAULT_NB },
    { city: "שדה צבי", neighborhoods: DEFAULT_NB },
    { city: "שדות ים", neighborhoods: DEFAULT_NB },
    { city: "שדות מיכה", neighborhoods: DEFAULT_NB },
    { city: "שדי אברהם", neighborhoods: DEFAULT_NB },
    { city: "שדי חמד", neighborhoods: DEFAULT_NB },
    { city: "שדי תרומות", neighborhoods: DEFAULT_NB },
    { city: "שדמה", neighborhoods: DEFAULT_NB },
    { city: "שדמות דבורה", neighborhoods: DEFAULT_NB },
    { city: "שדרות", neighborhoods: ["מרכז", "שכונה ב", "שכונת הדרים"] },
    { city: "שואבה", neighborhoods: DEFAULT_NB },
    { city: "שובה", neighborhoods: DEFAULT_NB },
    { city: "שובל", neighborhoods: DEFAULT_NB },
    { city: "שוהם", neighborhoods: DEFAULT_NB },
    { city: "שומרה", neighborhoods: DEFAULT_NB },
    { city: "שומריה", neighborhoods: DEFAULT_NB },
    { city: "שוקדה", neighborhoods: DEFAULT_NB },
    { city: "שורש", neighborhoods: DEFAULT_NB },
    { city: "שורשים", neighborhoods: DEFAULT_NB },
    { city: "שושנת העמקים", neighborhoods: DEFAULT_NB },
    { city: "שזור", neighborhoods: DEFAULT_NB },
    { city: "שחר", neighborhoods: DEFAULT_NB },
    { city: "שחרות", neighborhoods: DEFAULT_NB },
    { city: "שחרית", neighborhoods: DEFAULT_NB },
    { city: "שיבולים", neighborhoods: DEFAULT_NB },
    { city: "שיזף", neighborhoods: DEFAULT_NB },
    { city: "שיטים", neighborhoods: DEFAULT_NB },
    { city: "שילת", neighborhoods: DEFAULT_NB },
    { city: "שכניה", neighborhoods: DEFAULT_NB },
    { city: "שלווה", neighborhoods: DEFAULT_NB },
    { city: "שלווה במדבר", neighborhoods: DEFAULT_NB },
    { city: "שלוחות", neighborhoods: DEFAULT_NB },
    { city: "שלומי", neighborhoods: DEFAULT_NB },
    { city: "שלומית", neighborhoods: DEFAULT_NB },
    { city: "שמיר", neighborhoods: DEFAULT_NB },
    { city: "שמרת", neighborhoods: DEFAULT_NB },
    { city: "שמשית", neighborhoods: DEFAULT_NB },
    { city: "שניר", neighborhoods: DEFAULT_NB },
    { city: "שעל", neighborhoods: DEFAULT_NB },
    { city: "שעלבים", neighborhoods: DEFAULT_NB },
    { city: "שער אפרים", neighborhoods: DEFAULT_NB },
    { city: "שער הגולן", neighborhoods: DEFAULT_NB },
    { city: "שער העמקים", neighborhoods: DEFAULT_NB },
    { city: "שער מנשה", neighborhoods: DEFAULT_NB },
    { city: "שפיים", neighborhoods: DEFAULT_NB },
    { city: "שפיר", neighborhoods: DEFAULT_NB },
    { city: "שפר", neighborhoods: DEFAULT_NB },
    { city: "שפרעם", neighborhoods: DEFAULT_NB },
    { city: "שקף", neighborhoods: DEFAULT_NB },
    { city: "שרונה", neighborhoods: DEFAULT_NB },
    { city: "שריגים (לי-און)", neighborhoods: DEFAULT_NB },
    { city: "שריד", neighborhoods: DEFAULT_NB },
    { city: "שרשרת", neighborhoods: DEFAULT_NB },
    { city: "שתולה", neighborhoods: DEFAULT_NB },
    { city: "שתולים", neighborhoods: DEFAULT_NB },

    // ============== ת ==============
    { city: "תאשור", neighborhoods: DEFAULT_NB },
    { city: "תדהר", neighborhoods: DEFAULT_NB },
    { city: "תובל", neighborhoods: DEFAULT_NB },
    { city: "תושיה", neighborhoods: DEFAULT_NB },
    { city: "תימורים", neighborhoods: DEFAULT_NB },
    { city: "תירוש", neighborhoods: DEFAULT_NB },
    { city: "תל אביב יפו", neighborhoods: ["רמת אביב", "פלורנטין", "נווה צדק", "יפו העתיקה", "רמת החייל", "הצפון הישן", "הצפון החדש", "לב העיר", "נמל תל אביב", "רוטשילד", "אבו כביר", "אוהל משה", "אופק הים", "אורות", "אזור תעשייה עבר הירקון", "אזורי חן", "אפקה", "ביצרון", "גבעת הרצל", "גבעת עלייה", "גבעת עמל ב'", "המשתלה", "הקריה", "יד אליהו", "יפו ג'", "יפו ד'", "ישגב", "כוכב הצפון", "כפר שלם", "כרם התימנים", "כרם ישראל", "כרם משה", "לב תל אביב", "מאה שערים", "מגדלי נאמן", "שכונת מחלול", "מחנה יהודה", "מחנה יוסף", "מנשייה", "מעוז אביב", "מרכז בעלי מלאכה", "מרכז מסחרי", "מתחם לודוויפול", "נאות אפקה", "נווה אביבים", "נווה אליעזר", "נווה ברבור", "נווה חן", "נווה כפיר", "נווה עופר", "נווה צה\"ל", "נווה שאנן", "נווה שלום", "נווה שרת", "נופי ים", "נורדיה", "נחלת בנימין", "נחלת יצחק (מזרח)", "נחלת יצחק (מרכז)", "פארק צמרת", "שכונת פקידי אפ\"ק", "פרדס דכה", "צהלה", "צהלון", "צוקי אביב", "קריית המלאכה", "קריית מאיר", "קריית שאול", "קריית שלום", "רמת אביב ג'", "רמת הטייסים", "רמת השרון", "רמת ישראל", "שיכון בבלי", "שיכון דן", "שיכון צמרת", "שיכוני חיסכון", "שכונות עבר הירקון", "שכונת אחווה", "שכונת הארגזים", "שכונת התקווה", "שכונת ידידיה", "שכונת למד", "שכונת מונטיפיורי", "שכונת עזרא", "שכונת רביבים", "שכונת שבזי", "שכונת שפאק", "שכונת שפירא", "שרונה", "תל ברוך", "תל חיים", "תל נורדאו"] },
    { city: "תל יוסף", neighborhoods: DEFAULT_NB },
    { city: "תל יצחק", neighborhoods: DEFAULT_NB },
    { city: "תל מונד", neighborhoods: ["מרכז", "שכונת הגנים"] },
    { city: "תל עדשים", neighborhoods: DEFAULT_NB },
    { city: "תל קציר", neighborhoods: DEFAULT_NB },
    { city: "תל שבע", neighborhoods: DEFAULT_NB },
    { city: "תל תאומים", neighborhoods: DEFAULT_NB },
    { city: "תלמי אליהו", neighborhoods: DEFAULT_NB },
    { city: "תלמי אלעזר", neighborhoods: DEFAULT_NB },
    { city: "תלמי ביל\"ו", neighborhoods: DEFAULT_NB },
    { city: "תלמי יוסף", neighborhoods: DEFAULT_NB },
    { city: "תלמי יחיאל", neighborhoods: DEFAULT_NB },
    { city: "תלמי יפה", neighborhoods: DEFAULT_NB },
    { city: "תלמים", neighborhoods: DEFAULT_NB },
    { city: "תמרת", neighborhoods: DEFAULT_NB },
    { city: "תנובות", neighborhoods: DEFAULT_NB },
    { city: "תעוז", neighborhoods: DEFAULT_NB },
    { city: "תפרח", neighborhoods: DEFAULT_NB },
    { city: "תקומה", neighborhoods: DEFAULT_NB },
    { city: "תרום", neighborhoods: DEFAULT_NB },

    // ============== ישובים ביו"ש ==============
    { city: "אביגיל", neighborhoods: DEFAULT_NB },
    { city: "איתמר", neighborhoods: DEFAULT_NB },
    { city: "אלון מורה", neighborhoods: DEFAULT_NB },
    { city: "אלון שבות", neighborhoods: DEFAULT_NB },
    { city: "אלמוג", neighborhoods: DEFAULT_NB },
    { city: "אלעזר", neighborhoods: DEFAULT_NB },
    { city: "אלפי מנשה", neighborhoods: DEFAULT_NB },
    { city: "אלקנה", neighborhoods: DEFAULT_NB },
    { city: "אפרת", neighborhoods: DEFAULT_NB },
    { city: "ארגמן", neighborhoods: DEFAULT_NB },
    { city: "אריאל", neighborhoods: ["מרכז", "גבעה א", "גבעה ב"] },
    { city: "אש קודש", neighborhoods: DEFAULT_NB },
    { city: "אשכולות", neighborhoods: DEFAULT_NB },
    { city: "בית אל", neighborhoods: DEFAULT_NB },
    { city: "בית אריה-עופרים", neighborhoods: DEFAULT_NB },
    { city: "בית הערבה", neighborhoods: DEFAULT_NB },
    { city: "בית חגי", neighborhoods: DEFAULT_NB },
    { city: "בית חגלה", neighborhoods: DEFAULT_NB },
    { city: "בית חורון", neighborhoods: DEFAULT_NB },
    { city: "בית יתיר", neighborhoods: DEFAULT_NB },
    { city: "ביתר עילית", neighborhoods: DEFAULT_NB },
    { city: "בקעות", neighborhoods: DEFAULT_NB },
    { city: "ברוכין", neighborhoods: DEFAULT_NB },
    { city: "ברקן", neighborhoods: DEFAULT_NB },
    { city: "בת עין", neighborhoods: DEFAULT_NB },
    { city: "גבע בנימין", neighborhoods: DEFAULT_NB },
    { city: "גבעון החדשה", neighborhoods: DEFAULT_NB },
    { city: "גבעות", neighborhoods: DEFAULT_NB },
    { city: "גבעת הראל", neighborhoods: DEFAULT_NB },
    { city: "גבעת זאב", neighborhoods: DEFAULT_NB },
    { city: "גוש אדומים", neighborhoods: DEFAULT_NB },
    { city: "גוש טלמונים", neighborhoods: DEFAULT_NB },
    { city: "גוש מכמש", neighborhoods: DEFAULT_NB },
    { city: "גוש מערבא", neighborhoods: DEFAULT_NB },
    { city: "גוש עציון", neighborhoods: DEFAULT_NB },
    { city: "גוש שילה", neighborhoods: DEFAULT_NB },
    { city: "גוש שקד", neighborhoods: DEFAULT_NB },
    { city: "גיתית", neighborhoods: DEFAULT_NB },
    { city: "גלגל", neighborhoods: DEFAULT_NB },
    { city: "גני מודיעין", neighborhoods: ["מרכז", "שכונה א", "שכונה ב"] },
    { city: "גנים", neighborhoods: DEFAULT_NB },
    { city: "דולב", neighborhoods: DEFAULT_NB },
    { city: "הדר בית\"ר", neighborhoods: DEFAULT_NB },
    { city: "הר אדר", neighborhoods: DEFAULT_NB },
    { city: "הר ברכה", neighborhoods: DEFAULT_NB },
    { city: "ורד יריחו", neighborhoods: DEFAULT_NB },
    { city: "היישוב היהודי בחברון", neighborhoods: DEFAULT_NB },
    { city: "חוות טליה", neighborhoods: DEFAULT_NB },
    { city: "חוות יאיר", neighborhoods: DEFAULT_NB },
    { city: "חומש", neighborhoods: DEFAULT_NB },
    { city: "חיננית", neighborhoods: DEFAULT_NB },
    { city: "חמדת", neighborhoods: DEFAULT_NB },
    { city: "חמרה", neighborhoods: DEFAULT_NB },
    { city: "חרשה", neighborhoods: DEFAULT_NB },
    { city: "חשמונאים", neighborhoods: ["מרכז", "שכונה א", "שכונה ב"] },
    { city: "טלמון", neighborhoods: DEFAULT_NB },
    { city: "טנא עומרים", neighborhoods: DEFAULT_NB },
    { city: "ייט\"ב", neighborhoods: DEFAULT_NB },
    { city: "יפית", neighborhoods: DEFAULT_NB },
    { city: "יצהר", neighborhoods: DEFAULT_NB },
    { city: "יקיר", neighborhoods: DEFAULT_NB },
    { city: "כדים", neighborhoods: DEFAULT_NB },
    { city: "כוכב השחר", neighborhoods: DEFAULT_NB },
    { city: "כוכב יעקב", neighborhoods: DEFAULT_NB },
    { city: "כפר אדומים", neighborhoods: DEFAULT_NB },
    { city: "כפר האורנים", neighborhoods: DEFAULT_NB },
    { city: "כפר עציון", neighborhoods: DEFAULT_NB },
    { city: "כפר תפוח", neighborhoods: DEFAULT_NB },
    { city: "כרם רעים", neighborhoods: DEFAULT_NB },
    { city: "כרמי צור", neighborhoods: DEFAULT_NB },
    { city: "כרמל", neighborhoods: DEFAULT_NB },
    { city: "מבוא דותן", neighborhoods: DEFAULT_NB },
    { city: "מבוא חורון", neighborhoods: DEFAULT_NB },
    { city: "מבואות יריחו", neighborhoods: DEFAULT_NB },
    { city: "מגדל עוז", neighborhoods: DEFAULT_NB },
    { city: "מגדלים", neighborhoods: DEFAULT_NB },
    { city: "מגרון", neighborhoods: DEFAULT_NB },
    { city: "מיצד", neighborhoods: DEFAULT_NB },
    { city: "מכורה", neighborhoods: DEFAULT_NB },
    { city: "מעון", neighborhoods: DEFAULT_NB },
    { city: "מעלה אדומים", neighborhoods: ["מרכז", "מצפה נבו", "מגדלים", "אדמות יוסף"] },
    { city: "מעלה אפרים", neighborhoods: DEFAULT_NB },
    { city: "מעלה חבר", neighborhoods: DEFAULT_NB },
    { city: "מעלה לבונה", neighborhoods: DEFAULT_NB },
    { city: "מעלה מכמש", neighborhoods: DEFAULT_NB },
    { city: "מעלה שומרון", neighborhoods: DEFAULT_NB },
    { city: "מצפה דני", neighborhoods: DEFAULT_NB },
    { city: "מצפה יריחו", neighborhoods: DEFAULT_NB },
    { city: "מצפה כרמים", neighborhoods: DEFAULT_NB },
    { city: "מצפה שלם", neighborhoods: DEFAULT_NB },
    { city: "משואה", neighborhoods: DEFAULT_NB },
    { city: "משכיות", neighborhoods: DEFAULT_NB },
    { city: "מתתיהו", neighborhoods: DEFAULT_NB },
    { city: "נגוהות", neighborhoods: DEFAULT_NB },
    { city: "נווה דניאל", neighborhoods: DEFAULT_NB },
    { city: "נווה צוף", neighborhoods: DEFAULT_NB },
    { city: "נופי נחמיה", neighborhoods: DEFAULT_NB },
    { city: "נופי פרת", neighborhoods: DEFAULT_NB },
    { city: "נופים", neighborhoods: DEFAULT_NB },
    { city: "נוקדים", neighborhoods: DEFAULT_NB },
    { city: "נחליאל", neighborhoods: DEFAULT_NB },
    { city: "ניל\"י", neighborhoods: DEFAULT_NB },
    { city: "נעלה", neighborhoods: DEFAULT_NB },
    { city: "נעמה", neighborhoods: DEFAULT_NB },
    { city: "נערן", neighborhoods: DEFAULT_NB },
    { city: "נתיב הגדוד", neighborhoods: DEFAULT_NB },
    { city: "סוסיא", neighborhoods: DEFAULT_NB },
    { city: "סלעית", neighborhoods: DEFAULT_NB },
    { city: "סנסנה", neighborhoods: DEFAULT_NB },
    { city: "עדי עד", neighborhoods: DEFAULT_NB },
    { city: "עטרת", neighborhoods: DEFAULT_NB },
    { city: "עלי", neighborhoods: DEFAULT_NB },
    { city: "עלי זהב", neighborhoods: DEFAULT_NB },
    { city: "עלמון", neighborhoods: DEFAULT_NB },
    { city: "עמנואל", neighborhoods: DEFAULT_NB },
    { city: "ענב", neighborhoods: DEFAULT_NB },
    { city: "עפרה", neighborhoods: DEFAULT_NB },
    { city: "עץ אפרים", neighborhoods: DEFAULT_NB },
    { city: "עשהאל", neighborhoods: DEFAULT_NB },
    { city: "עתניאל", neighborhoods: DEFAULT_NB },
    { city: "פדואל", neighborhoods: DEFAULT_NB },
    { city: "פסגות", neighborhoods: DEFAULT_NB },
    { city: "פצאל", neighborhoods: DEFAULT_NB },
    { city: "צופים", neighborhoods: DEFAULT_NB },
    { city: "קדומים", neighborhoods: DEFAULT_NB },
    { city: "קידה", neighborhoods: DEFAULT_NB },
    { city: "קידר", neighborhoods: DEFAULT_NB },
    { city: "קליה", neighborhoods: DEFAULT_NB },
    { city: "קריית ארבע", neighborhoods: DEFAULT_NB },
    { city: "קריית נטפים", neighborhoods: DEFAULT_NB },
    { city: "קרני שומרון", neighborhoods: DEFAULT_NB },
    { city: "ראש צורים", neighborhoods: DEFAULT_NB },
    { city: "רבבה", neighborhoods: DEFAULT_NB },
    { city: "רועי", neighborhoods: DEFAULT_NB },
    { city: "רותם", neighborhoods: DEFAULT_NB },
    { city: "רחלים", neighborhoods: DEFAULT_NB },
    { city: "ריחן", neighborhoods: DEFAULT_NB },
    { city: "רימונים", neighborhoods: DEFAULT_NB },
    { city: "רמת קדרון", neighborhoods: DEFAULT_NB },
    { city: "שא-נור", neighborhoods: DEFAULT_NB },
    { city: "שבי שומרון", neighborhoods: DEFAULT_NB },
    { city: "שדמות מחולה", neighborhoods: DEFAULT_NB },
    { city: "שילה", neighborhoods: DEFAULT_NB },
    { city: "שמעה", neighborhoods: DEFAULT_NB },
    { city: "שני", neighborhoods: DEFAULT_NB },
    { city: "שער שומרון", neighborhoods: DEFAULT_NB },
    { city: "שערי תקווה", neighborhoods: DEFAULT_NB },
    { city: "שקד", neighborhoods: DEFAULT_NB },
    { city: "תומר", neighborhoods: DEFAULT_NB },
    { city: "תל ציון", neighborhoods: DEFAULT_NB },
    { city: "תלם", neighborhoods: DEFAULT_NB },
    { city: "תקוע", neighborhoods: DEFAULT_NB },
];

// Convenience: plain object for components that need Record<string, string[]>
// אם עיר מופיעה פעמיים — מאחדים שכונות ומסירים כפילויות
export const citiesAndNeighborhoods: Record<string, string[]> = (() => {
    const map = new Map<string, string[]>();
    for (const entry of citiesData) {
        const existing = map.get(entry.city) ?? [];
        const combined = [...existing, ...entry.neighborhoods];
        map.set(entry.city, Array.from(new Set(combined)));
    }
    return Object.fromEntries(map);
})();

export const DEFAULT_NEIGHBORHOOD = "קרית משה";
export const LS_KEY = "shchuna_selected_neighborhood"; // localStorage key
